[package]
name = "distvirt-worker"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "distvirt-worker"
path = "src/main.rs"

[dependencies]
clap.workspace = true
env_logger.workspace = true
anyhow.workspace = true
base64.workspace = true
prost.workspace = true
prost-types = "0.14"
tokio-stream.workspace = true
containerd-client = { git = "https://github.com/containerd/rust-extensions.git", rev = "8cf0ee65b9def500e978d48f88954530aa14c835" }
distvirt-common = { path = "../common" }
distvirt-guest-protocol = { path = "../guest-protocol" }
distvirt-activator = { path = "../activator" }
distvirt-worker-protocol = { path = "../worker-protocol" }
libc.workspace = true
log.workspace = true
oci-spec = "0.9"
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
smoltcp = { workspace = true, features = ["socket-udp"] }
tokio = { workspace = true, features = ["rt-multi-thread", "net", "macros", "io-util", "time", "process", "sync", "fs"] }
tonic.workspace = true
yamux.workspace = true
tokio-util = { workspace = true, features = ["io-util"] }
futures-lite.workspace = true
boringtun.workspace = true
rand.workspace = true
sha2 = "0.10"
hickory-resolver = "0.25"
zerocopy = { version = "0.8", features = ["derive"] }
async-trait = "0.1"
snow = "0.10"
tar = "0.4"
uuid = { version = "1.22.0", features = ["v4"] }

[dev-dependencies]
env_logger.workspace = true
etherparse.workspace = true
tokio = { workspace = true, features = ["signal"] }
