[package]
name = "distvirt-compose"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
compose_spec = "0.3"
distvirt-worker-protocol = { path = "../distvirt-worker-protocol" }
futures-lite = "2.6.1"
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "io-util", "sync"] }

[dev-dependencies]
tempfile = "3"
