[package]
name = "distvirt-orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
log = "0.4"
distvirt-worker-protocol = { path = "../distvirt-worker-protocol" }
tokio = { version = "1", features = ["rt", "time", "sync", "macros", "net", "rt-multi-thread", "test-util"] }
anyhow = "1"
tonic = "0.12"
prost = "0.13"
tokio-stream = "0.1"
distvirt-client-protocol = { path = "../distvirt-client-protocol" }
x25519-dalek = { version = "2", features = ["static_secrets"] }
rand = "0.8"
futures-lite = "2.6.1"
toml = "0.8"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
proptest = "1"
stateright = "0.31"
tokio-test = "0.4"

[[bin]]
name = "distvirt-orchestrator"
path = "src/main.rs"

[[test]]
name = "shell_integration"

[[test]]
name = "e2e"
