[workspace]
resolver = "3"
members = ["crates/common", "crates/worker", "crates/worker-protocol", "crates/guest-protocol", "crates/cli", "crates/activator", "crates/guest-init", "crates/orchestrator", "crates/client-protocol", "crates/tests", "crates/sm-router", "crates/sm-router-macros", "crates/untyped-vec", "crates/client"]
exclude = ["activators/test-echo", "activators/tcp", "activators/spin", "activators/http2", "activators/postgres", "activators/activator-types", "sdk/distvirt-sdk-core", "guest-image/test-containers"]

[profile.guest]
inherits = "release"
panic = "abort"
lto = true
strip = true
opt-level = "s"
