apiVersion: v1
kind: Namespace

metadata:
  name: test

network:
  subnet: 172.16.0.0/24

workloads:
  web:
    containers:
      - image: docker.io/library/nginx:latest
    services:
      web:
        activation:
          tcp:
            ports: [80]
            idle_timeout: 5m
        expose:
          - container_port: 80
            host_port: 8080
            protocol: tcp

  app:
    containers:
      - image: docker.io/library/alpine:latest
        args: ["sh", "-c", "while true; do echo hello from app; wget -qO- http://web:80 > /dev/null && echo 'reached web!'; sleep 2; done"]
        env:
          MY_VAR: "testing"
