apiVersion: v1
kind: Namespace

metadata:
  name: test

network:
  subnet: 172.16.0.0/24

workloads:
  web:
    volumes:
      - name: config
        config_data:
          files:
            - path: Caddyfile
              content: |
                :80 {
                    respond "Hello from distvirt!" 200
                }
    containers:
      - image: docker.io/library/caddy:2.11.2-alpine
        args: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
        volume_mounts:
          - name: config
            mount_path: /etc/caddy
    respects_demand: false
    suspend_on_idle: false
  db:
    volumes:
      - name: data
        empty_dir:
          size_mb: 512
    containers:
      - image: docker.io/library/postgres:14.22-trixie
        env:
          POSTGRES_PASSWORD: password
        volume_mounts: 
          - name: data
            mount_path: "/var/lib/postgresql"
    respects_demand: false
    suspend_on_idle: false
