apiVersion: v1
kind: Namespace

metadata:
  name: test

network:
  subnet: 172.16.0.0/24

workloads:
  web:
    containers:
      #- image: docker.io/library/nginx:latest
      - image: docker.io/library/caddy:2.11.2-alpine
    respects_demand: false
    suspend_on_idle: false
  db:
    containers:
      - image: docker.io/library/postgres:14.22-trixie
        env:
          POSTGRES_PASSWORD: password
    respects_demand: false
    suspend_on_idle: false
