//! JSON-based protocol for communication between the unprivileged parent
//! process and the privileged TUN setup helper.
//!
//! Messages are sent over the same Unix socket used for `SCM_RIGHTS` fd
//! passing, using the existing length-prefixed framing from [`super::fd_pass`].

use std::os::fd::{OwnedFd, RawFd};

use anyhow::Context;
use serde::{Deserialize, Serialize};

use super::fd_pass;

/// Messages sent from the privileged helper to the parent process.
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum HelperToParent {
    /// TUN device was created and configured successfully.
    /// Sent together with the TUN fd via `SCM_RIGHTS`.
    SetupResult {
        nonce: String,
        device_name: String,
        /// Nonce generated by the helper for bidirectional validation.
        helper_nonce: String,
    },
    /// An error occurred during setup.
    Error { nonce: String, message: String },
}

/// Messages sent from the parent process to the privileged helper.
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ParentToHelper {
    /// Acknowledge the helper's nonce, completing bidirectional validation.
    Ack { helper_nonce: String },
    /// Request the helper to perform teardown (remove DNS/routes) and exit.
    Teardown,
}

/// Send a `HelperToParent` message, optionally with an attached file descriptor.
pub fn send_helper_msg(
    sock: &OwnedFd,
    fd: Option<RawFd>,
    msg: &HelperToParent,
) -> anyhow::Result<()> {
    let payload = serde_json::to_vec(msg).context("serialize helper message")?;
    fd_pass::send_msg(sock, fd, &payload)
}

/// Send a `ParentToHelper` message (no fd).
pub fn send_parent_msg(sock: &OwnedFd, msg: &ParentToHelper) -> anyhow::Result<()> {
    let payload = serde_json::to_vec(msg).context("serialize parent message")?;
    fd_pass::send_msg(sock, None, &payload)
}

/// Receive a `HelperToParent` message, possibly with an attached file descriptor.
pub fn recv_helper_msg(sock: &OwnedFd) -> anyhow::Result<(HelperToParent, Option<OwnedFd>)> {
    let mut buf = [0u8; 4096];
    let (n, maybe_fd) = fd_pass::recv_fd(sock, &mut buf)?
        .ok_or_else(|| anyhow::anyhow!("helper closed connection without sending a message"))?;
    let msg: HelperToParent =
        serde_json::from_slice(&buf[..n]).context("deserialize helper message")?;
    Ok((msg, maybe_fd))
}

/// Receive a `ParentToHelper` message. Returns `None` on EOF (socket closed).
pub fn recv_parent_msg(sock: &OwnedFd) -> anyhow::Result<Option<ParentToHelper>> {
    let mut buf = [0u8; 4096];
    match fd_pass::recv_fd(sock, &mut buf)? {
        None => Ok(None),
        Some((n, _)) => {
            let msg: ParentToHelper =
                serde_json::from_slice(&buf[..n]).context("deserialize parent message")?;
            Ok(Some(msg))
        }
    }
}
