[package]
name = "distvirt-activator"
version = "0.1.0"
edition = "2024"

[dependencies]
activator-types = { path = "../../activators/activator-types" }
anyhow.workspace = true
etherparse.workspace = true
log.workspace = true
smoltcp.workspace = true
wasmtime = { version = "43", features = ["component-model"] }
wasmtime-wasi = "43"

[dev-dependencies]
activator-types = { path = "../../activators/activator-types", features = ["test-helpers"] }
tempfile.workspace = true
