[package]
name = "distvirt-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
distvirt-client-protocol = { path = "../distvirt-client-protocol" }
serde = { version = "1", features = ["derive"] }
serde-saphyr = "0.0.22"
saphyr = "0.0.6"
annotate-snippets = "0.11"
log = "0.4"

[dev-dependencies]
tempfile = "3"
