[package]
name = "distvirt-client"
version = "0.1.0"
edition = "2024"

[dependencies]
snafu = "0.9"
anyhow.workspace = true
distvirt-client-protocol = { path = "../client-protocol" }
dirs.workspace = true
log.workspace = true
serde.workspace = true
serde-saphyr = "0.0.22"
saphyr = "0.0.6"
annotate-snippets = "0.12"
toml.workspace = true
tonic.workspace = true
boringtun.workspace = true
base64.workspace = true
libc.workspace = true
nix = { version = "0.31", features = ["ioctl"] }
tokio = { workspace = true, features = ["net", "time", "io-util", "sync"] }
rand.workspace = true
smoltcp = { workspace = true, features = ["socket-udp", "socket-dns"] }
tempfile.workspace = true
