// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
/// L3 flow — fabric-tracked packet correlation by (src, dst, ports, protocol) tuple.
pub type PacketFlow = u64;
/// L4 stream handle — fabric-managed TCP connection with byte-stream semantics.
pub type StreamHandle = u64;
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum IpProtocol {
    Tcp,
    Udp,
    Other,
}
impl ::core::fmt::Debug for IpProtocol {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            IpProtocol::Tcp => f.debug_tuple("IpProtocol::Tcp").finish(),
            IpProtocol::Udp => f.debug_tuple("IpProtocol::Udp").finish(),
            IpProtocol::Other => f.debug_tuple("IpProtocol::Other").finish(),
        }
    }
}
impl IpProtocol {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> IpProtocol {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => IpProtocol::Tcp,
            1 => IpProtocol::Udp,
            2 => IpProtocol::Other,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
#[derive(Clone)]
pub struct PacketInfo {
    pub flow: PacketFlow,
    pub src_addr: _rt::Vec<u8>,
    pub dst_addr: _rt::Vec<u8>,
    pub src_port: u16,
    pub dst_port: u16,
    pub protocol: IpProtocol,
    pub tcp_flags: Option<u8>,
    pub payload: _rt::Vec<u8>,
    pub raw_frame: _rt::Vec<u8>,
}
impl ::core::fmt::Debug for PacketInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PacketInfo")
            .field("flow", &self.flow)
            .field("src-addr", &self.src_addr)
            .field("dst-addr", &self.dst_addr)
            .field("src-port", &self.src_port)
            .field("dst-port", &self.dst_port)
            .field("protocol", &self.protocol)
            .field("tcp-flags", &self.tcp_flags)
            .field("payload", &self.payload)
            .field("raw-frame", &self.raw_frame)
            .finish()
    }
}
#[derive(Clone)]
pub struct StreamDataEvent {
    pub s: StreamHandle,
    pub data: _rt::Vec<u8>,
}
impl ::core::fmt::Debug for StreamDataEvent {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("StreamDataEvent")
            .field("s", &self.s)
            .field("data", &self.data)
            .finish()
    }
}
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum PacketDecision {
    Buffered,
    Drop,
}
impl ::core::fmt::Debug for PacketDecision {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            PacketDecision::Buffered => {
                f.debug_tuple("PacketDecision::Buffered").finish()
            }
            PacketDecision::Drop => f.debug_tuple("PacketDecision::Drop").finish(),
        }
    }
}
impl PacketDecision {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> PacketDecision {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => PacketDecision::Buffered,
            1 => PacketDecision::Drop,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum ConnectResult {
    Ok,
    Refused,
    Timeout,
}
impl ::core::fmt::Debug for ConnectResult {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            ConnectResult::Ok => f.debug_tuple("ConnectResult::Ok").finish(),
            ConnectResult::Refused => f.debug_tuple("ConnectResult::Refused").finish(),
            ConnectResult::Timeout => f.debug_tuple("ConnectResult::Timeout").finish(),
        }
    }
}
impl ConnectResult {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> ConnectResult {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => ConnectResult::Ok,
            1 => ConnectResult::Refused,
            2 => ConnectResult::Timeout,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct UpstreamConnectResultEvent {
    pub s: StreamHandle,
    pub outcome: ConnectResult,
}
impl ::core::fmt::Debug for UpstreamConnectResultEvent {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("UpstreamConnectResultEvent")
            .field("s", &self.s)
            .field("outcome", &self.outcome)
            .finish()
    }
}
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum BackendNeed {
    None,
    Traffic,
    Active,
}
impl ::core::fmt::Debug for BackendNeed {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            BackendNeed::None => f.debug_tuple("BackendNeed::None").finish(),
            BackendNeed::Traffic => f.debug_tuple("BackendNeed::Traffic").finish(),
            BackendNeed::Active => f.debug_tuple("BackendNeed::Active").finish(),
        }
    }
}
impl BackendNeed {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> BackendNeed {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => BackendNeed::None,
            1 => BackendNeed::Traffic,
            2 => BackendNeed::Active,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum LogLevel {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
}
impl ::core::fmt::Debug for LogLevel {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            LogLevel::Trace => f.debug_tuple("LogLevel::Trace").finish(),
            LogLevel::Debug => f.debug_tuple("LogLevel::Debug").finish(),
            LogLevel::Info => f.debug_tuple("LogLevel::Info").finish(),
            LogLevel::Warn => f.debug_tuple("LogLevel::Warn").finish(),
            LogLevel::Error => f.debug_tuple("LogLevel::Error").finish(),
        }
    }
}
impl LogLevel {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> LogLevel {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => LogLevel::Trace,
            1 => LogLevel::Debug,
            2 => LogLevel::Info,
            3 => LogLevel::Warn,
            4 => LogLevel::Error,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
#[derive(Clone)]
pub struct LogAction {
    pub level: LogLevel,
    pub message: _rt::String,
}
impl ::core::fmt::Debug for LogAction {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("LogAction")
            .field("level", &self.level)
            .field("message", &self.message)
            .finish()
    }
}
#[derive(Clone)]
pub enum Event {
    BackendAvailable(bool),
    Tick,
    Packet(PacketInfo),
    StreamOpen(StreamHandle),
    StreamData(StreamDataEvent),
    StreamClose(StreamHandle),
    UpstreamConnectResult(UpstreamConnectResultEvent),
    UpstreamData(StreamDataEvent),
    UpstreamClose(StreamHandle),
}
impl ::core::fmt::Debug for Event {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            Event::BackendAvailable(e) => {
                f.debug_tuple("Event::BackendAvailable").field(e).finish()
            }
            Event::Tick => f.debug_tuple("Event::Tick").finish(),
            Event::Packet(e) => f.debug_tuple("Event::Packet").field(e).finish(),
            Event::StreamOpen(e) => f.debug_tuple("Event::StreamOpen").field(e).finish(),
            Event::StreamData(e) => f.debug_tuple("Event::StreamData").field(e).finish(),
            Event::StreamClose(e) => {
                f.debug_tuple("Event::StreamClose").field(e).finish()
            }
            Event::UpstreamConnectResult(e) => {
                f.debug_tuple("Event::UpstreamConnectResult").field(e).finish()
            }
            Event::UpstreamData(e) => {
                f.debug_tuple("Event::UpstreamData").field(e).finish()
            }
            Event::UpstreamClose(e) => {
                f.debug_tuple("Event::UpstreamClose").field(e).finish()
            }
        }
    }
}
#[derive(Clone)]
pub enum Action {
    SetBackendNeed(BackendNeed),
    Log(LogAction),
    PacketDecision((PacketFlow, PacketDecision)),
    PacketReply((PacketFlow, _rt::Vec<u8>)),
    ReplayPacket(_rt::Vec<u8>),
    DownstreamSend((StreamHandle, _rt::Vec<u8>)),
    DownstreamClose(StreamHandle),
    PauseDownstream(StreamHandle),
    ResumeDownstream(StreamHandle),
    UpstreamConnect(u16),
    UpstreamSend((StreamHandle, _rt::Vec<u8>)),
    UpstreamClose(StreamHandle),
    PauseUpstream(StreamHandle),
    ResumeUpstream(StreamHandle),
}
impl ::core::fmt::Debug for Action {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            Action::SetBackendNeed(e) => {
                f.debug_tuple("Action::SetBackendNeed").field(e).finish()
            }
            Action::Log(e) => f.debug_tuple("Action::Log").field(e).finish(),
            Action::PacketDecision(e) => {
                f.debug_tuple("Action::PacketDecision").field(e).finish()
            }
            Action::PacketReply(e) => {
                f.debug_tuple("Action::PacketReply").field(e).finish()
            }
            Action::ReplayPacket(e) => {
                f.debug_tuple("Action::ReplayPacket").field(e).finish()
            }
            Action::DownstreamSend(e) => {
                f.debug_tuple("Action::DownstreamSend").field(e).finish()
            }
            Action::DownstreamClose(e) => {
                f.debug_tuple("Action::DownstreamClose").field(e).finish()
            }
            Action::PauseDownstream(e) => {
                f.debug_tuple("Action::PauseDownstream").field(e).finish()
            }
            Action::ResumeDownstream(e) => {
                f.debug_tuple("Action::ResumeDownstream").field(e).finish()
            }
            Action::UpstreamConnect(e) => f.debug_tuple("Action::UpstreamConnect").field(e).finish(),
            Action::UpstreamSend(e) => {
                f.debug_tuple("Action::UpstreamSend").field(e).finish()
            }
            Action::UpstreamClose(e) => {
                f.debug_tuple("Action::UpstreamClose").field(e).finish()
            }
            Action::PauseUpstream(e) => {
                f.debug_tuple("Action::PauseUpstream").field(e).finish()
            }
            Action::ResumeUpstream(e) => {
                f.debug_tuple("Action::ResumeUpstream").field(e).finish()
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_process_events_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base34 = arg0;
    let len34 = arg1;
    let mut result34 = _rt::Vec::with_capacity(len34);
    for i in 0..len34 {
        let base = base34.add(i * (24 + 8 * ::core::mem::size_of::<*const u8>()));
        let e34 = {
            let l0 = i32::from(*base.add(0).cast::<u8>());
            let v33 = match l0 {
                0 => {
                    let e33 = {
                        let l1 = i32::from(*base.add(8).cast::<u8>());
                        _rt::bool_lift(l1 as u8)
                    };
                    Event::BackendAvailable(e33)
                }
                1 => Event::Tick,
                2 => {
                    let e33 = {
                        let l2 = *base.add(8).cast::<i64>();
                        let l3 = *base.add(16).cast::<*mut u8>();
                        let l4 = *base
                            .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len5 = l4;
                        let l6 = *base
                            .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l7 = *base
                            .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len8 = l7;
                        let l9 = i32::from(
                            *base
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u16>(),
                        );
                        let l10 = i32::from(
                            *base
                                .add(18 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u16>(),
                        );
                        let l11 = i32::from(
                            *base
                                .add(20 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>(),
                        );
                        let l12 = i32::from(
                            *base
                                .add(21 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>(),
                        );
                        let l14 = *base
                            .add(24 + 4 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l15 = *base
                            .add(24 + 5 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len16 = l15;
                        let l17 = *base
                            .add(24 + 6 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l18 = *base
                            .add(24 + 7 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len19 = l18;
                        PacketInfo {
                            flow: l2 as u64,
                            src_addr: _rt::Vec::from_raw_parts(l3.cast(), len5, len5),
                            dst_addr: _rt::Vec::from_raw_parts(l6.cast(), len8, len8),
                            src_port: l9 as u16,
                            dst_port: l10 as u16,
                            protocol: IpProtocol::_lift(l11 as u8),
                            tcp_flags: match l12 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l13 = i32::from(
                                            *base
                                                .add(22 + 4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        l13 as u8
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            payload: _rt::Vec::from_raw_parts(l14.cast(), len16, len16),
                            raw_frame: _rt::Vec::from_raw_parts(l17.cast(), len19, len19),
                        }
                    };
                    Event::Packet(e33)
                }
                3 => {
                    let e33 = {
                        let l20 = *base.add(8).cast::<i64>();
                        l20 as u64
                    };
                    Event::StreamOpen(e33)
                }
                4 => {
                    let e33 = {
                        let l21 = *base.add(8).cast::<i64>();
                        let l22 = *base.add(16).cast::<*mut u8>();
                        let l23 = *base
                            .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len24 = l23;
                        StreamDataEvent {
                            s: l21 as u64,
                            data: _rt::Vec::from_raw_parts(l22.cast(), len24, len24),
                        }
                    };
                    Event::StreamData(e33)
                }
                5 => {
                    let e33 = {
                        let l25 = *base.add(8).cast::<i64>();
                        l25 as u64
                    };
                    Event::StreamClose(e33)
                }
                6 => {
                    let e33 = {
                        let l26 = *base.add(8).cast::<i64>();
                        let l27 = i32::from(*base.add(16).cast::<u8>());
                        UpstreamConnectResultEvent {
                            s: l26 as u64,
                            outcome: ConnectResult::_lift(l27 as u8),
                        }
                    };
                    Event::UpstreamConnectResult(e33)
                }
                7 => {
                    let e33 = {
                        let l28 = *base.add(8).cast::<i64>();
                        let l29 = *base.add(16).cast::<*mut u8>();
                        let l30 = *base
                            .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len31 = l30;
                        StreamDataEvent {
                            s: l28 as u64,
                            data: _rt::Vec::from_raw_parts(l29.cast(), len31, len31),
                        }
                    };
                    Event::UpstreamData(e33)
                }
                n => {
                    debug_assert_eq!(n, 8, "invalid enum discriminant");
                    let e33 = {
                        let l32 = *base.add(8).cast::<i64>();
                        l32 as u64
                    };
                    Event::UpstreamClose(e33)
                }
            };
            v33
        };
        result34.push(e34);
    }
    _rt::cabi_dealloc(base34, len34 * (24 + 8 * ::core::mem::size_of::<*const u8>()), 8);
    let result35 = T::process_events(result34);
    let ptr36 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec47 = result35;
    let len47 = vec47.len();
    let layout47 = _rt::alloc::Layout::from_size_align_unchecked(
        vec47.len() * (16 + 2 * ::core::mem::size_of::<*const u8>()),
        8,
    );
    let result47 = if layout47.size() != 0 {
        let ptr = _rt::alloc::alloc(layout47).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout47);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec47.into_iter().enumerate() {
        let base = result47.add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
        {
            match e {
                Action::SetBackendNeed(e) => {
                    *base.add(0).cast::<u8>() = (0i32) as u8;
                    *base.add(8).cast::<u8>() = (e.clone() as i32) as u8;
                }
                Action::Log(e) => {
                    *base.add(0).cast::<u8>() = (1i32) as u8;
                    let LogAction { level: level37, message: message37 } = e;
                    *base.add(8).cast::<u8>() = (level37.clone() as i32) as u8;
                    let vec38 = (message37.into_bytes()).into_boxed_slice();
                    let ptr38 = vec38.as_ptr().cast::<u8>();
                    let len38 = vec38.len();
                    ::core::mem::forget(vec38);
                    *base
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len38;
                    *base
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr38.cast_mut();
                }
                Action::PacketDecision(e) => {
                    *base.add(0).cast::<u8>() = (2i32) as u8;
                    let (t39_0, t39_1) = e;
                    *base.add(8).cast::<i64>() = _rt::as_i64(t39_0);
                    *base.add(16).cast::<u8>() = (t39_1.clone() as i32) as u8;
                }
                Action::PacketReply(e) => {
                    *base.add(0).cast::<u8>() = (3i32) as u8;
                    let (t40_0, t40_1) = e;
                    *base.add(8).cast::<i64>() = _rt::as_i64(t40_0);
                    let vec41 = (t40_1).into_boxed_slice();
                    let ptr41 = vec41.as_ptr().cast::<u8>();
                    let len41 = vec41.len();
                    ::core::mem::forget(vec41);
                    *base
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len41;
                    *base.add(16).cast::<*mut u8>() = ptr41.cast_mut();
                }
                Action::ReplayPacket(e) => {
                    *base.add(0).cast::<u8>() = (4i32) as u8;
                    let vec42 = (e).into_boxed_slice();
                    let ptr42 = vec42.as_ptr().cast::<u8>();
                    let len42 = vec42.len();
                    ::core::mem::forget(vec42);
                    *base
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len42;
                    *base.add(8).cast::<*mut u8>() = ptr42.cast_mut();
                }
                Action::DownstreamSend(e) => {
                    *base.add(0).cast::<u8>() = (5i32) as u8;
                    let (t43_0, t43_1) = e;
                    *base.add(8).cast::<i64>() = _rt::as_i64(t43_0);
                    let vec44 = (t43_1).into_boxed_slice();
                    let ptr44 = vec44.as_ptr().cast::<u8>();
                    let len44 = vec44.len();
                    ::core::mem::forget(vec44);
                    *base
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len44;
                    *base.add(16).cast::<*mut u8>() = ptr44.cast_mut();
                }
                Action::DownstreamClose(e) => {
                    *base.add(0).cast::<u8>() = (6i32) as u8;
                    *base.add(8).cast::<i64>() = _rt::as_i64(e);
                }
                Action::PauseDownstream(e) => {
                    *base.add(0).cast::<u8>() = (7i32) as u8;
                    *base.add(8).cast::<i64>() = _rt::as_i64(e);
                }
                Action::ResumeDownstream(e) => {
                    *base.add(0).cast::<u8>() = (8i32) as u8;
                    *base.add(8).cast::<i64>() = _rt::as_i64(e);
                }
                Action::UpstreamConnect(e) => {
                    *base.add(0).cast::<u8>() = (9i32) as u8;
                    *base.add(8).cast::<u16>() = e;
                }
                Action::UpstreamSend(e) => {
                    *base.add(0).cast::<u8>() = (10i32) as u8;
                    let (t45_0, t45_1) = e;
                    *base.add(8).cast::<i64>() = _rt::as_i64(t45_0);
                    let vec46 = (t45_1).into_boxed_slice();
                    let ptr46 = vec46.as_ptr().cast::<u8>();
                    let len46 = vec46.len();
                    ::core::mem::forget(vec46);
                    *base
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len46;
                    *base.add(16).cast::<*mut u8>() = ptr46.cast_mut();
                }
                Action::UpstreamClose(e) => {
                    *base.add(0).cast::<u8>() = (11i32) as u8;
                    *base.add(8).cast::<i64>() = _rt::as_i64(e);
                }
                Action::PauseUpstream(e) => {
                    *base.add(0).cast::<u8>() = (12i32) as u8;
                    *base.add(8).cast::<i64>() = _rt::as_i64(e);
                }
                Action::ResumeUpstream(e) => {
                    *base.add(0).cast::<u8>() = (13i32) as u8;
                    *base.add(8).cast::<i64>() = _rt::as_i64(e);
                }
            }
        }
    }
    *ptr36.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len47;
    *ptr36.add(0).cast::<*mut u8>() = result47;
    ptr36
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_process_events<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base17 = l0;
    let len17 = l1;
    for i in 0..len17 {
        let base = base17.add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
        {
            let l2 = i32::from(*base.add(0).cast::<u8>());
            match l2 {
                0 => {}
                1 => {
                    let l3 = *base
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l4 = *base
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l3, l4, 1);
                }
                2 => {}
                3 => {
                    let l5 = *base.add(16).cast::<*mut u8>();
                    let l6 = *base
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base7 = l5;
                    let len7 = l6;
                    _rt::cabi_dealloc(base7, len7 * 1, 1);
                }
                4 => {
                    let l8 = *base.add(8).cast::<*mut u8>();
                    let l9 = *base
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base10 = l8;
                    let len10 = l9;
                    _rt::cabi_dealloc(base10, len10 * 1, 1);
                }
                5 => {
                    let l11 = *base.add(16).cast::<*mut u8>();
                    let l12 = *base
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base13 = l11;
                    let len13 = l12;
                    _rt::cabi_dealloc(base13, len13 * 1, 1);
                }
                6 => {}
                7 => {}
                8 => {}
                9 => {}
                10 => {
                    let l14 = *base.add(16).cast::<*mut u8>();
                    let l15 = *base
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base16 = l14;
                    let len16 = l15;
                    _rt::cabi_dealloc(base16, len16 * 1, 1);
                }
                11 => {}
                12 => {}
                _ => {}
            }
        }
    }
    _rt::cabi_dealloc(base17, len17 * (16 + 2 * ::core::mem::size_of::<*const u8>()), 8);
}
pub trait Guest {
    fn process_events(events: _rt::Vec<Event>) -> _rt::Vec<Action>;
}
#[doc(hidden)]
macro_rules! __export_world_activator_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "process-events")] unsafe extern "C" fn
        export_process_events(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_process_events_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "cabi_post_process-events")] unsafe extern "C" fn
        _post_return_process_events(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_process_events::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_activator_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_activator_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_activator_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_activator_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:distvirt:activator:activator:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1119] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xdf\x07\x01A\x02\x01\
A#\x01w\x03\0\x0bpacket-flow\x03\0\0\x01w\x03\0\x0dstream-handle\x03\0\x02\x01m\x03\
\x03tcp\x03udp\x05other\x03\0\x0bip-protocol\x03\0\x04\x01p}\x01k}\x01r\x09\x04f\
low\x01\x08src-addr\x06\x08dst-addr\x06\x08src-port{\x08dst-port{\x08protocol\x05\
\x09tcp-flags\x07\x07payload\x06\x09raw-frame\x06\x03\0\x0bpacket-info\x03\0\x08\
\x01r\x02\x01s\x03\x04data\x06\x03\0\x11stream-data-event\x03\0\x0a\x01m\x02\x08\
buffered\x04drop\x03\0\x0fpacket-decision\x03\0\x0c\x01m\x03\x02ok\x07refused\x07\
timeout\x03\0\x0econnect-result\x03\0\x0e\x01r\x02\x01s\x03\x07outcome\x0f\x03\0\
\x1dupstream-connect-result-event\x03\0\x10\x01m\x03\x04none\x07traffic\x06activ\
e\x03\0\x0cbackend-need\x03\0\x12\x01m\x05\x05trace\x05debug\x04info\x04warn\x05\
error\x03\0\x09log-level\x03\0\x14\x01r\x02\x05level\x15\x07messages\x03\0\x0alo\
g-action\x03\0\x16\x01q\x09\x11backend-available\x01\x7f\0\x04tick\0\0\x06packet\
\x01\x09\0\x0bstream-open\x01\x03\0\x0bstream-data\x01\x0b\0\x0cstream-close\x01\
\x03\0\x17upstream-connect-result\x01\x11\0\x0dupstream-data\x01\x0b\0\x0eupstre\
am-close\x01\x03\0\x03\0\x05event\x03\0\x18\x01o\x02\x01\x0d\x01o\x02\x01\x06\x01\
o\x02\x03\x06\x01q\x0e\x10set-backend-need\x01\x13\0\x03log\x01\x17\0\x0fpacket-\
decision\x01\x1a\0\x0cpacket-reply\x01\x1b\0\x0dreplay-packet\x01\x06\0\x0fdowns\
tream-send\x01\x1c\0\x10downstream-close\x01\x03\0\x10pause-downstream\x01\x03\0\
\x11resume-downstream\x01\x03\0\x10upstream-connect\0\0\x0dupstream-send\x01\x1c\
\0\x0eupstream-close\x01\x03\0\x0epause-upstream\x01\x03\0\x0fresume-upstream\x01\
\x03\0\x03\0\x06action\x03\0\x1d\x01p\x19\x01p\x1e\x01@\x01\x06events\x1f\0\x20\x04\
\0\x0eprocess-events\x01!\x04\0\x1cdistvirt:activator/activator\x04\0\x0b\x0f\x01\
\0\x09activator\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\
\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
