[package]
name = "guest-init"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "init"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-channel = "2"
async-executor = "1"
async-io = "2"
distvirt-guest-protocol = { path = "../guest-protocol" }
env_logger.workspace = true
futures.workspace = true
libc.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
yamux.workspace = true
