[package]
name = "guest-init"
version = "0.1.0"
edition = "2024"

[lib]
name = "guest_init"
path = "src/lib.rs"

[[bin]]
name = "init"
path = "src/main.rs"

[features]
test-support = ["tokio"]

[dependencies]
anyhow.workspace = true
async-channel = "2"
async-executor = "1"
async-io = "2"
distvirt-guest-protocol = { path = "../guest-protocol" }
env_logger.workspace = true
futures.workspace = true
futures-timer = "3"
libc.workspace = true
parking_lot = { version = "0.12", features = ["send_guard"] }
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "time"], optional = true }
yamux.workspace = true
