# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: distvirt/client/v1/client.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    AsyncIterable,
    AsyncIterator,
    Dict,
    Iterable,
    List,
    Optional,
    Union,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ExposeProtocol(betterproto.Enum):
    UNSPECIFIED = 0
    TCP = 1
    UDP = 2


class NamespaceState(betterproto.Enum):
    UNSPECIFIED = 0
    CREATING = 1
    ACTIVE = 2
    DESTROYING = 3


class BackendNeed(betterproto.Enum):
    UNSPECIFIED = 0
    NONE = 1
    TRAFFIC = 2
    ACTIVE = 3


class PodState(betterproto.Enum):
    UNSPECIFIED = 0
    LAUNCHING = 1
    RUNNING = 2
    SUSPENDING = 3
    SUSPENDED = 4
    RESUMING = 5


class EndpointActivationTrigger(betterproto.Enum):
    UNSPECIFIED = 0
    TRAFFIC = 1


class IdleTimerCancelReason(betterproto.Enum):
    UNSPECIFIED = 0
    NEW_TRAFFIC = 1


class EndpointDeactivationReason(betterproto.Enum):
    UNSPECIFIED = 0
    IDLE_TIMEOUT = 1
    FORCE_DEACTIVATE = 2


@dataclass(eq=False, repr=False)
class NamespaceSpec(betterproto.Message):
    network: "NetworkConfig" = betterproto.message_field(1)
    workloads: Dict[str, "WorkloadSpec"] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    services: Dict[str, "ServiceSpec"] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass(eq=False, repr=False)
class WorkloadSpec(betterproto.Message):
    network: "PodNetworkConfig" = betterproto.message_field(1)
    containers: List["ContainerSpec"] = betterproto.message_field(2)
    suspend_on_idle: bool = betterproto.bool_field(3)
    resources: "ResourceRequirements" = betterproto.message_field(4)
    activation: "ActivationSpec" = betterproto.message_field(5)
    respects_demand: bool = betterproto.bool_field(6)
    """
    If true, the workload respects demand signals and starts dormant.
     If false (default), the workload is always-on.
    """

    volumes: List["VolumeSpec"] = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class ResourceValues(betterproto.Message):
    memory_mb: int = betterproto.uint64_field(1)
    vcpus: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ResourceRequirements(betterproto.Message):
    requests: "ResourceValues" = betterproto.message_field(1)
    limits: "ResourceValues" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ContainerSpec(betterproto.Message):
    name: str = betterproto.string_field(1)
    image: str = betterproto.string_field(2)
    config: "ContainerConfig" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class PodNetworkConfig(betterproto.Message):
    ip: str = betterproto.string_field(1)
    mac: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ServiceSpec(betterproto.Message):
    workload_id: str = betterproto.string_field(1)
    network: "ServiceNetworkConfig" = betterproto.message_field(2)
    activation: "ActivationSpec" = betterproto.message_field(3)
    expose: List["ExposeSpec"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class ActivationSpec(betterproto.Message):
    activator: "ActivatorConfig" = betterproto.message_field(1)
    buffer_policy: "ServicePolicy" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ActivatorConfig(betterproto.Message):
    tcp: "TcpActivator" = betterproto.message_field(1, group="activator")
    http2: "Http2Activator" = betterproto.message_field(2, group="activator")
    passthrough: "PassthroughActivator" = betterproto.message_field(
        3, group="activator"
    )


@dataclass(eq=False, repr=False)
class PassthroughActivator(betterproto.Message):
    idle_timeout_ms: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class TcpActivator(betterproto.Message):
    ports: List[int] = betterproto.uint32_field(1)
    idle_timeout_ms: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class Http2Activator(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ContainerConfig(betterproto.Message):
    entrypoint: List[str] = betterproto.string_field(1)
    args: List[str] = betterproto.string_field(2)
    env: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    working_dir: str = betterproto.string_field(6)
    user: str = betterproto.string_field(7)
    hostname: str = betterproto.string_field(8)
    tty: bool = betterproto.bool_field(9)
    volume_mounts: List["VolumeMountSpec"] = betterproto.message_field(10)


@dataclass(eq=False, repr=False)
class VolumeSpec(betterproto.Message):
    name: str = betterproto.string_field(1)
    empty_dir: "EmptyDirVolume" = betterproto.message_field(2, group="volume_type")
    config_data: "ConfigDataVolume" = betterproto.message_field(3, group="volume_type")


@dataclass(eq=False, repr=False)
class EmptyDirVolume(betterproto.Message):
    size_mb: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class ConfigDataVolume(betterproto.Message):
    files: List["ConfigDataFile"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ConfigDataFile(betterproto.Message):
    path: str = betterproto.string_field(1)
    content: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class VolumeMountSpec(betterproto.Message):
    name: str = betterproto.string_field(1)
    mount_path: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ServiceNetworkConfig(betterproto.Message):
    ip: str = betterproto.string_field(1)
    mac: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class NetworkConfig(betterproto.Message):
    subnet: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ExposeSpec(betterproto.Message):
    container_port: int = betterproto.uint32_field(1)
    host_port: int = betterproto.uint32_field(2)
    protocol: "ExposeProtocol" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class ServicePolicy(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CreateNamespaceRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    spec: "NamespaceSpec" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CreateNamespaceResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class UpdateNamespaceRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    spec: "NamespaceSpec" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class UpdateNamespaceResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DeleteNamespaceRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DeleteNamespaceResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetNamespaceStatusRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetNamespaceStatusResponse(betterproto.Message):
    status: "NamespaceStatusReport" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListNamespacesRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListNamespacesResponse(betterproto.Message):
    namespaces: List["NamespaceStatusReport"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class NamespaceStatusReport(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    state: "NamespaceState" = betterproto.enum_field(2)
    workloads: Dict[str, "WorkloadStatusReport"] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    services: Dict[str, "ServiceStatusReport"] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    pods: Dict[str, "PodStatusReportEntry"] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass(eq=False, repr=False)
class PodStatusReportEntry(betterproto.Message):
    workload_id: str = betterproto.string_field(1)
    worker_id: str = betterproto.string_field(2)
    ip: str = betterproto.string_field(3)
    state: "PodState" = betterproto.enum_field(4)


@dataclass(eq=False, repr=False)
class WorkloadStatusReport(betterproto.Message):
    state: "WorkloadState" = betterproto.message_field(1)
    spliced: bool = betterproto.bool_field(2)
    ip: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class WorkloadState(betterproto.Message):
    dormant: "WorkloadDormant" = betterproto.message_field(1, group="state")
    waiting_for_spec: "WorkloadWaitingForSpec" = betterproto.message_field(
        2, group="state"
    )
    launching: "WorkloadLaunching" = betterproto.message_field(3, group="state")
    running: "WorkloadRunning" = betterproto.message_field(4, group="state")
    suspending: "WorkloadSuspending" = betterproto.message_field(5, group="state")
    suspended: "WorkloadSuspended" = betterproto.message_field(6, group="state")
    retry_backoff: "WorkloadRetryBackoff" = betterproto.message_field(7, group="state")
    failed: "WorkloadFailed" = betterproto.message_field(8, group="state")
    completed: "WorkloadCompleted" = betterproto.message_field(9, group="state")


@dataclass(eq=False, repr=False)
class WorkloadDormant(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WorkloadWaitingForSpec(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WorkloadLaunching(betterproto.Message):
    pod_id: str = betterproto.string_field(1)
    worker_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WorkloadRunning(betterproto.Message):
    pod_id: str = betterproto.string_field(1)
    worker_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WorkloadSuspending(betterproto.Message):
    pod_id: str = betterproto.string_field(1)
    worker_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WorkloadSuspended(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WorkloadRetryBackoff(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WorkloadFailed(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WorkloadCompleted(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ServiceStatusReport(betterproto.Message):
    workload_id: str = betterproto.string_field(1)
    state: "ServiceState" = betterproto.message_field(2)
    activation_enabled: bool = betterproto.bool_field(3)
    spliced: bool = betterproto.bool_field(4)
    ip: str = betterproto.string_field(5)
    mac: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class ServiceState(betterproto.Message):
    pending: "ServicePending" = betterproto.message_field(1, group="state")
    idle: "ServiceIdle" = betterproto.message_field(2, group="state")
    need_backend: "ServiceNeedBackend" = betterproto.message_field(3, group="state")
    active: "ServiceActive" = betterproto.message_field(4, group="state")


@dataclass(eq=False, repr=False)
class ServicePending(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ServiceIdle(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ServiceNeedBackend(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ServiceActive(betterproto.Message):
    pod_id: str = betterproto.string_field(1)
    worker_id: str = betterproto.string_field(2)
    backend_need: "BackendNeed" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class SpliceRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workload_id: str = betterproto.string_field(2)
    local_worker_id: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SpliceResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class UnspliceRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workload_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class UnspliceResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class PatchNamespaceRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workloads: Dict[str, "WorkloadSpec"] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    """Upsert: create if absent, replace if present"""

    services: Dict[str, "ServiceSpec"] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    remove_workloads: List[str] = betterproto.string_field(4)
    """Remove by name (ignored if absent)"""

    remove_services: List[str] = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class PatchNamespaceResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DeactivateWorkloadRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workload_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class DeactivateWorkloadResponse(betterproto.Message):
    deactivated: bool = betterproto.bool_field(1)
    reason: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ConnectNetworkRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    client_public_key: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class ConnectNetworkResponse(betterproto.Message):
    server_public_key: bytes = betterproto.bytes_field(1)
    endpoint: str = betterproto.string_field(2)
    client_ip: str = betterproto.string_field(3)
    subnet: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class DisconnectNetworkRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    client_public_key: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class DisconnectNetworkResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CloneNamespaceRequest(betterproto.Message):
    source_namespace_id: str = betterproto.string_field(1)
    target_namespace_id: str = betterproto.string_field(2)
    overrides: "NamespaceOverrides" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class CloneNamespaceResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class NamespaceOverrides(betterproto.Message):
    workloads: Dict[str, "WorkloadOverrides"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    services: Dict[str, "ServiceOverrides"] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass(eq=False, repr=False)
class WorkloadOverrides(betterproto.Message):
    image: Optional[str] = betterproto.string_field(1, optional=True)
    env_overrides: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class ServiceOverrides(betterproto.Message):
    workload_id: Optional[str] = betterproto.string_field(1, optional=True)


@dataclass(eq=False, repr=False)
class ListWorkersRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListWorkersResponse(betterproto.Message):
    workers: List["WorkerInfo"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetWorkerRequest(betterproto.Message):
    worker_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetWorkerResponse(betterproto.Message):
    worker: "WorkerInfo" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WorkerInfo(betterproto.Message):
    worker_id: str = betterproto.string_field(1)
    max_pods: int = betterproto.uint32_field(2)
    available_memory_mb: int = betterproto.uint64_field(3)
    active_pods: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ListPodsRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ListPodsResponse(betterproto.Message):
    pods: List["PodInfo"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class PodInfo(betterproto.Message):
    pod_id: str = betterproto.string_field(1)
    workload_id: str = betterproto.string_field(2)
    worker_id: str = betterproto.string_field(3)
    ip: str = betterproto.string_field(4)
    mac: str = betterproto.string_field(5)
    state: "PodState" = betterproto.enum_field(6)


@dataclass(eq=False, repr=False)
class StreamEventsRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workload_ids: List[str] = betterproto.string_field(2)
    service_ids: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class NamespaceEvent(betterproto.Message):
    timestamp_unix_ms: int = betterproto.int64_field(1)
    workload: "WorkloadEvent" = betterproto.message_field(2, group="event")
    pod: "PodEvent" = betterproto.message_field(3, group="event")
    endpoint: "EndpointEvent" = betterproto.message_field(4, group="event")


@dataclass(eq=False, repr=False)
class WorkloadEvent(betterproto.Message):
    workload_id: str = betterproto.string_field(1)
    demand_changed: "WorkloadDemandChanged" = betterproto.message_field(
        2, group="event"
    )
    spliced: "WorkloadSpliced" = betterproto.message_field(3, group="event")
    unspliced: "WorkloadUnspliced" = betterproto.message_field(4, group="event")


@dataclass(eq=False, repr=False)
class WorkloadDemandChanged(betterproto.Message):
    demanding_services: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class WorkloadSpliced(betterproto.Message):
    worker_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class WorkloadUnspliced(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class PodEvent(betterproto.Message):
    pod_id: str = betterproto.string_field(1)
    workload_id: str = betterproto.string_field(2)
    created: "PodCreated" = betterproto.message_field(3, group="event")
    scheduled: "PodScheduled" = betterproto.message_field(4, group="event")
    running: "PodRunning" = betterproto.message_field(5, group="event")
    stopped: "PodStopped" = betterproto.message_field(6, group="event")
    failed: "PodFailed" = betterproto.message_field(7, group="event")
    suspending: "PodSuspending" = betterproto.message_field(8, group="event")
    suspended: "PodSuspended" = betterproto.message_field(9, group="event")
    suspend_failed: "PodSuspendFailed" = betterproto.message_field(10, group="event")
    resuming: "PodResuming" = betterproto.message_field(11, group="event")
    displaced: "PodDisplaced" = betterproto.message_field(12, group="event")
    reaped: "PodReaped" = betterproto.message_field(13, group="event")


@dataclass(eq=False, repr=False)
class PodCreated(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class PodScheduled(betterproto.Message):
    worker_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class PodRunning(betterproto.Message):
    worker_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class PodStopped(betterproto.Message):
    exit_code: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class PodFailed(betterproto.Message):
    reason: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class PodSuspending(betterproto.Message):
    worker_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class PodSuspended(betterproto.Message):
    worker_id: str = betterproto.string_field(1)
    snapshot_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class PodSuspendFailed(betterproto.Message):
    reason: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class PodResuming(betterproto.Message):
    worker_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class PodDisplaced(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class PodReaped(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class EndpointEvent(betterproto.Message):
    endpoint_id: str = betterproto.string_field(1)
    service_id: Optional[str] = betterproto.string_field(2, optional=True)
    workload_id: Optional[str] = betterproto.string_field(3, optional=True)
    activated: "EndpointActivated" = betterproto.message_field(4, group="event")
    backend_ready: "EndpointBackendReady" = betterproto.message_field(5, group="event")
    idle_timer_started: "EndpointIdleTimerStarted" = betterproto.message_field(
        6, group="event"
    )
    idle_timer_cancelled: "EndpointIdleTimerCancelled" = betterproto.message_field(
        7, group="event"
    )
    idle_timeout_fired: "EndpointIdleTimeoutFired" = betterproto.message_field(
        8, group="event"
    )
    deactivated: "EndpointDeactivated" = betterproto.message_field(9, group="event")


@dataclass(eq=False, repr=False)
class EndpointActivated(betterproto.Message):
    trigger: "EndpointActivationTrigger" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class EndpointBackendReady(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class EndpointIdleTimerStarted(betterproto.Message):
    timeout_ms: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class EndpointIdleTimerCancelled(betterproto.Message):
    reason: "IdleTimerCancelReason" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class EndpointIdleTimeoutFired(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class EndpointDeactivated(betterproto.Message):
    reason: "EndpointDeactivationReason" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class AttachWorkloadInput(betterproto.Message):
    start: "AttachStart" = betterproto.message_field(1, group="input")
    stdin: "AttachStdin" = betterproto.message_field(2, group="input")
    resize: "AttachResize" = betterproto.message_field(3, group="input")


@dataclass(eq=False, repr=False)
class AttachStart(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workload_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class AttachStdin(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class AttachResize(betterproto.Message):
    cols: int = betterproto.uint32_field(1)
    rows: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class AttachWorkloadOutput(betterproto.Message):
    started: "AttachStarted" = betterproto.message_field(1, group="output")
    stdout: "AttachStdout" = betterproto.message_field(2, group="output")
    stderr: "AttachStderr" = betterproto.message_field(3, group="output")
    exited: "AttachExited" = betterproto.message_field(4, group="output")


@dataclass(eq=False, repr=False)
class AttachStarted(betterproto.Message):
    tty: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class AttachStdout(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class AttachStderr(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class AttachExited(betterproto.Message):
    exit_code: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class StreamLogsRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workload_id: Optional[str] = betterproto.string_field(2, optional=True)
    container_ids: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class WatchNamespaceStatusRequest(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class NamespaceStatusEvent(betterproto.Message):
    status: "NamespaceStatusReport" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class LogChunk(betterproto.Message):
    workload_id: str = betterproto.string_field(1)
    data: bytes = betterproto.bytes_field(2)
    timestamp_unix_ms: int = betterproto.int64_field(3)
    container_id: str = betterproto.string_field(4)


class DistvirtClientStub(betterproto.ServiceStub):
    async def create_namespace(
        self,
        create_namespace_request: "CreateNamespaceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CreateNamespaceResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/CreateNamespace",
            create_namespace_request,
            CreateNamespaceResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_namespace(
        self,
        update_namespace_request: "UpdateNamespaceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "UpdateNamespaceResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/UpdateNamespace",
            update_namespace_request,
            UpdateNamespaceResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_namespace(
        self,
        delete_namespace_request: "DeleteNamespaceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeleteNamespaceResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/DeleteNamespace",
            delete_namespace_request,
            DeleteNamespaceResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_namespace_status(
        self,
        get_namespace_status_request: "GetNamespaceStatusRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetNamespaceStatusResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/GetNamespaceStatus",
            get_namespace_status_request,
            GetNamespaceStatusResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_namespaces(
        self,
        list_namespaces_request: "ListNamespacesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListNamespacesResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/ListNamespaces",
            list_namespaces_request,
            ListNamespacesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def splice(
        self,
        splice_request: "SpliceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SpliceResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/Splice",
            splice_request,
            SpliceResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def unsplice(
        self,
        unsplice_request: "UnspliceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "UnspliceResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/Unsplice",
            unsplice_request,
            UnspliceResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def deactivate_workload(
        self,
        deactivate_workload_request: "DeactivateWorkloadRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeactivateWorkloadResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/DeactivateWorkload",
            deactivate_workload_request,
            DeactivateWorkloadResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def patch_namespace(
        self,
        patch_namespace_request: "PatchNamespaceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PatchNamespaceResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/PatchNamespace",
            patch_namespace_request,
            PatchNamespaceResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def clone_namespace(
        self,
        clone_namespace_request: "CloneNamespaceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CloneNamespaceResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/CloneNamespace",
            clone_namespace_request,
            CloneNamespaceResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_workers(
        self,
        list_workers_request: "ListWorkersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListWorkersResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/ListWorkers",
            list_workers_request,
            ListWorkersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_worker(
        self,
        get_worker_request: "GetWorkerRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetWorkerResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/GetWorker",
            get_worker_request,
            GetWorkerResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_pods(
        self,
        list_pods_request: "ListPodsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListPodsResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/ListPods",
            list_pods_request,
            ListPodsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def connect_network(
        self,
        connect_network_request: "ConnectNetworkRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ConnectNetworkResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/ConnectNetwork",
            connect_network_request,
            ConnectNetworkResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def disconnect_network(
        self,
        disconnect_network_request: "DisconnectNetworkRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DisconnectNetworkResponse":
        return await self._unary_unary(
            "/distvirt.client.v1.DistvirtClient/DisconnectNetwork",
            disconnect_network_request,
            DisconnectNetworkResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def attach_workload(
        self,
        attach_workload_input_iterator: Union[
            AsyncIterable[AttachWorkloadInput], Iterable[AttachWorkloadInput]
        ],
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[AttachWorkloadOutput]:
        async for response in self._stream_stream(
            "/distvirt.client.v1.DistvirtClient/AttachWorkload",
            attach_workload_input_iterator,
            AttachWorkloadInput,
            AttachWorkloadOutput,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def watch_namespace_status(
        self,
        watch_namespace_status_request: "WatchNamespaceStatusRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[NamespaceStatusEvent]:
        async for response in self._unary_stream(
            "/distvirt.client.v1.DistvirtClient/WatchNamespaceStatus",
            watch_namespace_status_request,
            NamespaceStatusEvent,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def stream_logs(
        self,
        stream_logs_request: "StreamLogsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[LogChunk]:
        async for response in self._unary_stream(
            "/distvirt.client.v1.DistvirtClient/StreamLogs",
            stream_logs_request,
            LogChunk,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def stream_events(
        self,
        stream_events_request: "StreamEventsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[NamespaceEvent]:
        async for response in self._unary_stream(
            "/distvirt.client.v1.DistvirtClient/StreamEvents",
            stream_events_request,
            NamespaceEvent,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class DistvirtClientBase(ServiceBase):

    async def create_namespace(
        self, create_namespace_request: "CreateNamespaceRequest"
    ) -> "CreateNamespaceResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_namespace(
        self, update_namespace_request: "UpdateNamespaceRequest"
    ) -> "UpdateNamespaceResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_namespace(
        self, delete_namespace_request: "DeleteNamespaceRequest"
    ) -> "DeleteNamespaceResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_namespace_status(
        self, get_namespace_status_request: "GetNamespaceStatusRequest"
    ) -> "GetNamespaceStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_namespaces(
        self, list_namespaces_request: "ListNamespacesRequest"
    ) -> "ListNamespacesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def splice(self, splice_request: "SpliceRequest") -> "SpliceResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def unsplice(self, unsplice_request: "UnspliceRequest") -> "UnspliceResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def deactivate_workload(
        self, deactivate_workload_request: "DeactivateWorkloadRequest"
    ) -> "DeactivateWorkloadResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def patch_namespace(
        self, patch_namespace_request: "PatchNamespaceRequest"
    ) -> "PatchNamespaceResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def clone_namespace(
        self, clone_namespace_request: "CloneNamespaceRequest"
    ) -> "CloneNamespaceResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_workers(
        self, list_workers_request: "ListWorkersRequest"
    ) -> "ListWorkersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_worker(
        self, get_worker_request: "GetWorkerRequest"
    ) -> "GetWorkerResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_pods(
        self, list_pods_request: "ListPodsRequest"
    ) -> "ListPodsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def connect_network(
        self, connect_network_request: "ConnectNetworkRequest"
    ) -> "ConnectNetworkResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def disconnect_network(
        self, disconnect_network_request: "DisconnectNetworkRequest"
    ) -> "DisconnectNetworkResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def attach_workload(
        self, attach_workload_input_iterator: AsyncIterator[AttachWorkloadInput]
    ) -> AsyncIterator[AttachWorkloadOutput]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield AttachWorkloadOutput()

    async def watch_namespace_status(
        self, watch_namespace_status_request: "WatchNamespaceStatusRequest"
    ) -> AsyncIterator[NamespaceStatusEvent]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield NamespaceStatusEvent()

    async def stream_logs(
        self, stream_logs_request: "StreamLogsRequest"
    ) -> AsyncIterator[LogChunk]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield LogChunk()

    async def stream_events(
        self, stream_events_request: "StreamEventsRequest"
    ) -> AsyncIterator[NamespaceEvent]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield NamespaceEvent()

    async def __rpc_create_namespace(
        self,
        stream: "grpclib.server.Stream[CreateNamespaceRequest, CreateNamespaceResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.create_namespace(request)
        await stream.send_message(response)

    async def __rpc_update_namespace(
        self,
        stream: "grpclib.server.Stream[UpdateNamespaceRequest, UpdateNamespaceResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.update_namespace(request)
        await stream.send_message(response)

    async def __rpc_delete_namespace(
        self,
        stream: "grpclib.server.Stream[DeleteNamespaceRequest, DeleteNamespaceResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_namespace(request)
        await stream.send_message(response)

    async def __rpc_get_namespace_status(
        self,
        stream: "grpclib.server.Stream[GetNamespaceStatusRequest, GetNamespaceStatusResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_namespace_status(request)
        await stream.send_message(response)

    async def __rpc_list_namespaces(
        self,
        stream: "grpclib.server.Stream[ListNamespacesRequest, ListNamespacesResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_namespaces(request)
        await stream.send_message(response)

    async def __rpc_splice(
        self, stream: "grpclib.server.Stream[SpliceRequest, SpliceResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.splice(request)
        await stream.send_message(response)

    async def __rpc_unsplice(
        self, stream: "grpclib.server.Stream[UnspliceRequest, UnspliceResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.unsplice(request)
        await stream.send_message(response)

    async def __rpc_deactivate_workload(
        self,
        stream: "grpclib.server.Stream[DeactivateWorkloadRequest, DeactivateWorkloadResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.deactivate_workload(request)
        await stream.send_message(response)

    async def __rpc_patch_namespace(
        self,
        stream: "grpclib.server.Stream[PatchNamespaceRequest, PatchNamespaceResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.patch_namespace(request)
        await stream.send_message(response)

    async def __rpc_clone_namespace(
        self,
        stream: "grpclib.server.Stream[CloneNamespaceRequest, CloneNamespaceResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.clone_namespace(request)
        await stream.send_message(response)

    async def __rpc_list_workers(
        self, stream: "grpclib.server.Stream[ListWorkersRequest, ListWorkersResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_workers(request)
        await stream.send_message(response)

    async def __rpc_get_worker(
        self, stream: "grpclib.server.Stream[GetWorkerRequest, GetWorkerResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_worker(request)
        await stream.send_message(response)

    async def __rpc_list_pods(
        self, stream: "grpclib.server.Stream[ListPodsRequest, ListPodsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_pods(request)
        await stream.send_message(response)

    async def __rpc_connect_network(
        self,
        stream: "grpclib.server.Stream[ConnectNetworkRequest, ConnectNetworkResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.connect_network(request)
        await stream.send_message(response)

    async def __rpc_disconnect_network(
        self,
        stream: "grpclib.server.Stream[DisconnectNetworkRequest, DisconnectNetworkResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.disconnect_network(request)
        await stream.send_message(response)

    async def __rpc_attach_workload(
        self, stream: "grpclib.server.Stream[AttachWorkloadInput, AttachWorkloadOutput]"
    ) -> None:
        request = stream.__aiter__()
        await self._call_rpc_handler_server_stream(
            self.attach_workload,
            stream,
            request,
        )

    async def __rpc_watch_namespace_status(
        self,
        stream: "grpclib.server.Stream[WatchNamespaceStatusRequest, NamespaceStatusEvent]",
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.watch_namespace_status,
            stream,
            request,
        )

    async def __rpc_stream_logs(
        self, stream: "grpclib.server.Stream[StreamLogsRequest, LogChunk]"
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.stream_logs,
            stream,
            request,
        )

    async def __rpc_stream_events(
        self, stream: "grpclib.server.Stream[StreamEventsRequest, NamespaceEvent]"
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.stream_events,
            stream,
            request,
        )

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/distvirt.client.v1.DistvirtClient/CreateNamespace": grpclib.const.Handler(
                self.__rpc_create_namespace,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateNamespaceRequest,
                CreateNamespaceResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/UpdateNamespace": grpclib.const.Handler(
                self.__rpc_update_namespace,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateNamespaceRequest,
                UpdateNamespaceResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/DeleteNamespace": grpclib.const.Handler(
                self.__rpc_delete_namespace,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteNamespaceRequest,
                DeleteNamespaceResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/GetNamespaceStatus": grpclib.const.Handler(
                self.__rpc_get_namespace_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetNamespaceStatusRequest,
                GetNamespaceStatusResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/ListNamespaces": grpclib.const.Handler(
                self.__rpc_list_namespaces,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListNamespacesRequest,
                ListNamespacesResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/Splice": grpclib.const.Handler(
                self.__rpc_splice,
                grpclib.const.Cardinality.UNARY_UNARY,
                SpliceRequest,
                SpliceResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/Unsplice": grpclib.const.Handler(
                self.__rpc_unsplice,
                grpclib.const.Cardinality.UNARY_UNARY,
                UnspliceRequest,
                UnspliceResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/DeactivateWorkload": grpclib.const.Handler(
                self.__rpc_deactivate_workload,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeactivateWorkloadRequest,
                DeactivateWorkloadResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/PatchNamespace": grpclib.const.Handler(
                self.__rpc_patch_namespace,
                grpclib.const.Cardinality.UNARY_UNARY,
                PatchNamespaceRequest,
                PatchNamespaceResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/CloneNamespace": grpclib.const.Handler(
                self.__rpc_clone_namespace,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloneNamespaceRequest,
                CloneNamespaceResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/ListWorkers": grpclib.const.Handler(
                self.__rpc_list_workers,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListWorkersRequest,
                ListWorkersResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/GetWorker": grpclib.const.Handler(
                self.__rpc_get_worker,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetWorkerRequest,
                GetWorkerResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/ListPods": grpclib.const.Handler(
                self.__rpc_list_pods,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListPodsRequest,
                ListPodsResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/ConnectNetwork": grpclib.const.Handler(
                self.__rpc_connect_network,
                grpclib.const.Cardinality.UNARY_UNARY,
                ConnectNetworkRequest,
                ConnectNetworkResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/DisconnectNetwork": grpclib.const.Handler(
                self.__rpc_disconnect_network,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisconnectNetworkRequest,
                DisconnectNetworkResponse,
            ),
            "/distvirt.client.v1.DistvirtClient/AttachWorkload": grpclib.const.Handler(
                self.__rpc_attach_workload,
                grpclib.const.Cardinality.STREAM_STREAM,
                AttachWorkloadInput,
                AttachWorkloadOutput,
            ),
            "/distvirt.client.v1.DistvirtClient/WatchNamespaceStatus": grpclib.const.Handler(
                self.__rpc_watch_namespace_status,
                grpclib.const.Cardinality.UNARY_STREAM,
                WatchNamespaceStatusRequest,
                NamespaceStatusEvent,
            ),
            "/distvirt.client.v1.DistvirtClient/StreamLogs": grpclib.const.Handler(
                self.__rpc_stream_logs,
                grpclib.const.Cardinality.UNARY_STREAM,
                StreamLogsRequest,
                LogChunk,
            ),
            "/distvirt.client.v1.DistvirtClient/StreamEvents": grpclib.const.Handler(
                self.__rpc_stream_events,
                grpclib.const.Cardinality.UNARY_STREAM,
                StreamEventsRequest,
                NamespaceEvent,
            ),
        }
