[package]
name = "distvirt-orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
log.workspace = true
distvirt-common = { path = "../common" }
distvirt-worker-protocol = { path = "../worker-protocol" }
tokio = { workspace = true, features = ["rt", "time", "sync", "macros", "net", "rt-multi-thread", "test-util"] }
anyhow.workspace = true
tonic.workspace = true
prost.workspace = true
tokio-stream.workspace = true
distvirt-client-protocol = { path = "../client-protocol" }
distvirt-sm-router = { path = "../sm-router" }
x25519-dalek = { version = "2", features = ["static_secrets"] }
rand.workspace = true
subtle = "2"
futures-lite.workspace = true
yamux.workspace = true
toml.workspace = true
env_logger.workspace = true
clap.workspace = true

[features]
test-trace = []

[dev-dependencies]
distvirt-orchestrator = { path = ".", features = ["test-trace"] }
proptest = "1"
stateright = "0.31"
tokio-test = "0.4"

[[bin]]
name = "distvirt-orchestrator"
path = "src/main.rs"

[[test]]
name = "e2e"
