[package]
name = "distvirt-worker-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
log.workspace = true
prost.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["rt", "net", "io-util", "sync", "macros"] }
yamux.workspace = true
tokio-util.workspace = true
futures-lite.workspace = true

[build-dependencies]
prost-build = "0.14"
