//! # Signal Router
//!
//! A framework for coordinating state machines (SMs) that communicate through
//! typed signals, structural edges, and discrete events. The router maintains
//! the connectivity graph and mechanically propagates signal changes — SMs
//! contain only domain logic, never relationship bookkeeping.
//!
//! See [`docs/design/signal-router.md`] for full design rationale.
//!
//! ## Core concepts
//!
//! - **SM (State Machine):** An instance with identity, internal state, output
//!   signals, and a handler for incoming inputs. SMs contain domain logic only.
//!
//! - **Port:** An external boundary point (worker connection, management layer)
//!   that produces signals and sends events but has no state machine lifecycle.
//!
//! - **Signal:** A persistent current-value that an SM or port instance produces.
//!   Declared per type, keyed by `(instance_id, signal_type)`. The router uses
//!   `PartialEq` to detect changes — setting a signal to its current value is a
//!   no-op.
//!
//! - **Edge:** A unidirectional typed relationship between instances. Edges don't
//!   carry data directly — they define structure. Signals flow through edges as
//!   determined by aggregated input declarations.
//!
//! - **Aggregated Input:** A declared input on a consuming SM that specifies
//!   `(EdgeType, Signal)` source pairs and an [`Aggregator`] to combine them.
//!   The router re-aggregates whenever edges or source signals change.
//!
//! - **Event:** A one-shot discrete message between instances that have an edge
//!   relationship (checked in either direction). Not aggregated.
//!
//! Signals can have **invariants** — expressions that must hold at quiescence.
//! Violations are reported via the [tracing infrastructure](trace). See [`trace`]
//! module docs.
//!
//! ## Quick example
//!
//! ```rust,ignore
//! use distvirt_sm_router::{router, Aggregator, SmHandler, ListAggregator};
//!
//! // 1. Define ID types
//! #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
//! struct ServiceId(u64);
//!
//! #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
//! struct WorkloadId(u64);
//!
//! // 2. Define a custom aggregator
//! #[derive(Default)]
//! struct DemandAggregator;
//!
//! impl Aggregator for DemandAggregator {
//!     type Input = (ServiceId, bool);
//!     type Output = u32;
//!
//!     fn aggregate(&self, inputs: &[(ServiceId, bool)]) -> u32 {
//!         inputs.iter().filter(|(_, demand)| *demand).count() as u32
//!     }
//! }
//!
//! // 3. Declare the topology
//! router! {
//!     state_machines {
//!         Service(ServiceId, ServiceSm),
//!         Workload(WorkloadId, WorkloadSm),
//!     }
//!     ports {}
//!     signals {
//!         Service::Demand(bool),
//!     }
//!     edges {
//!         ServiceToWorkload: Service -> Workload,
//!     }
//!     events {}
//!     inputs {
//!         Workload::DemandInput {
//!             sources: [(ServiceToWorkload, Service::Demand)],
//!             aggregator: DemandAggregator,
//!         },
//!     }
//!     invariants {
//!         Service::Demand(*value),  // services should have demand at quiescence
//!     }
//! }
//!
//! // 4. Implement SM handlers (types are generated by the macro)
//! struct ServiceSm;
//!
//! impl<C: ServiceCtx> SmHandler<C> for ServiceSm {
//!     type Input = ServiceInput;   // generated enum (empty here — no inputs declared)
//!
//!     fn handle(&mut self, input: Self::Input, ctx: &mut C) {
//!         // handle inputs...
//!     }
//! }
//!
//! struct WorkloadSm {
//!     demand_count: u32,
//! }
//!
//! impl<C: WorkloadCtx> SmHandler<C> for WorkloadSm {
//!     type Input = WorkloadInput;  // generated: has DemandInput(u32) variant
//!
//!     fn handle(&mut self, input: Self::Input, ctx: &mut C) {
//!         match input {
//!             WorkloadInput::DemandInput(count) => {
//!                 self.demand_count = count;
//!             }
//!         }
//!     }
//! }
//!
//! // 5. Drive the router
//! let mut router = Router::new(16);
//!
//! let s1 = ServiceId(1);
//! let w1 = WorkloadId(1);
//!
//! router.create_service(s1, ServiceSm);
//! router.create_workload(w1, WorkloadSm { demand_count: 0 });
//!
//! // Establish edge and set signal
//! router.set_service_to_workload_edges(s1, vec![w1]);
//! router.set_service_demand(s1, true);
//!
//! // Propagate resolves all cascading effects
//! router.propagate();
//! // WorkloadSm received DemandInput(1)
//! ```
//!
//! ## Propagation model
//!
//! Signal propagation is organized into **sub-rounds**. When `propagate()` is
//! called, all cascading effects resolve before it returns. The propagation loop
//! alternates between two sub-round types:
//!
//! 1. **Input sub-round:** All dirty aggregated inputs are re-aggregated and
//!    delivered to SM handlers (only if the aggregated value actually changed —
//!    `PartialEq` comparison). Pending creates are materialized before delivery.
//! 2. **Event sub-round:** All pending events are delivered to receiver handlers
//!    (connectivity is verified — at least one edge must connect sender and
//!    receiver in either direction).
//!
//! Each handler call may update signals, edges, queue events, create or destroy
//! SMs via the context. These effects are applied atomically after the handler
//! returns, and feed into subsequent sub-rounds.
//!
//! The loop terminates when no dirty inputs, pending events, or pending creates
//! remain (quiescence). A configurable depth limit (passed to `Router::new()`)
//! prevents infinite loops. The router warns at `limit - 1` and panics at
//! `limit`.
//!
//! ### Effect application order
//!
//! When a handler returns, its buffered effects are applied in this order:
//! 1. **Creates** — buffered for materialization at the start of the next
//!    input sub-round
//! 2. **Signal changes** — applied immediately, dirty inputs enqueued
//! 3. **Edge changes** — applied immediately, dirty inputs enqueued
//! 4. **Events** — buffered into the pending events queue
//! 5. **Self-destruct** — instance removed, edges cleared (enqueues dirty inputs)
//!
//! ### Isolation within a sub-round
//!
//! Within a single sub-round, SM handlers are **fully independent**: no handler
//! observes the effects of another handler in the same sub-round. Signal changes,
//! edge changes, events, and creates produced by a handler all go into queues
//! processed in subsequent sub-rounds. This means the order in which different
//! SMs are processed within a sub-round does not affect the outcome.
//!
//! The only ordering that matters within a sub-round is when a **single SM**
//! receives multiple deliveries (e.g., two dirty inputs). The handler is called
//! sequentially for each, and the SM's internal state mutates between calls, so
//! the order can affect the SM's final state. The **lattice property** asserts
//! that this should not matter — any permutation of deliveries to a single SM
//! within a sub-round should produce the same final state at quiescence.
//!
//! ### Sub-round phasing
//!
//! The implementation processes input and event sub-rounds in a single loop
//! iteration (inputs first, then events). This is an optimization — conceptually
//! they are separate sub-rounds. Events queued during an input sub-round are
//! delivered in the immediately following event sub-round. Events queued during
//! an event sub-round are delivered in the next iteration's event sub-round.
//!
//! ## Self-destruct ordering guarantees
//!
//! When a handler calls `ctx.self_destruct()`, the following guarantees hold:
//!
//! - **Events before destruction:** Events queued by the handler (via
//!   `ctx.send_*()`) are delivered *before* the reactive effects of the
//!   destruction (edge removal, re-aggregation) take effect. Events are moved
//!   to the pending queue before `destroy_*()` runs, and the propagation loop
//!   processes pending events in the current round while new dirty inputs from
//!   edge clearing are deferred to the next round.
//!
//! - **No handler calls after self-destruct:** Once `self_destruct()` is called
//!   and effects are applied, the SM instance is removed from the instances map.
//!   All delivery paths (dirty input processing and event delivery) guard on
//!   instance existence and silently skip destroyed SMs. No further `handle()`
//!   calls will be made to the instance.

/// Reduces N signal values (from N incoming edges) into one aggregated input value.
///
/// The `Input` type is determined by the topology declaration:
/// - **Single-source inputs:** `(SourceId, SignalValue)` tuple
/// - **Multi-source inputs:** a generated enum with one variant per `(EdgeType, Signal)`
///   source pair, e.g. `enum DemandInputSource { ServiceDemand(ServiceId, bool), ... }`
///
/// Aggregators **must** handle the empty-input case (zero edges) — this produces the
/// "no data" baseline (e.g., `0`, empty vec). There is no concept of "uninitialized".
///
/// # Example
///
/// ```rust,ignore
/// #[derive(Default)]
/// struct CountTrueAggregator;
///
/// impl Aggregator for CountTrueAggregator {
///     type Input = (ServiceId, bool);
///     type Output = u32;
///
///     fn aggregate(&self, inputs: &[(ServiceId, bool)]) -> u32 {
///         inputs.iter().filter(|(_, v)| *v).count() as u32
///     }
/// }
/// ```
pub trait Aggregator {
    type Input;
    type Output;
    fn aggregate(&self, inputs: &[Self::Input]) -> Self::Output;
}

/// Handler trait for state machines. Each SM type implements this on its struct.
///
/// ## Generated types per SM
///
/// The [`router!`] macro generates several types for each declared SM (e.g. `Workload`):
///
/// - **`{Sm}Input`** (enum): One variant per aggregated input plus one per event
///   channel where this SM is the receiver. Exhaustive matching ensures all inputs
///   are handled.
///
/// - **`{Sm}Ctx`** (trait): The context interface that handlers program against.
///   Methods:
///   - `ctx.id()` — get this instance's ID
///   - `ctx.set_{signal}(value)` — update an output signal
///   - `ctx.set_{edge}_edges(targets)` — update outgoing edges
///   - `ctx.send_{event}(target, payload)` — send a discrete event
///   - `ctx.create_{sm}(sm)` — create a new SM (returns ID for auto-ID types)
///   - `ctx.self_destruct()` — destroy this instance after effects are applied
///
/// - **`{Sm}CtxConcrete`** (struct): The concrete [`Ctx`] implementation, generic
///   over an [`IdAllocator`]. Construct with `::new(id, &mut allocator)`, pass to
///   a handler, then call `.into_effects()` to extract the buffered effects. This
///   is useful for testing SM handlers in isolation or for model checking — you
///   supply your own allocator and inspect the resulting effects without a router.
///
/// - **`{Sm}Effects`** (struct): Owned record of all effects a handler produced.
///   Public fields for each signal (`Option<T>`), each outgoing edge
///   (`Option<Vec<TargetId>>`), plus `pending_events`, `pending_creates`, and
///   `pending_self_destruct`. The router applies these via internal
///   `apply_{sm}_effects`, but they can also be inspected directly for testing
///   or model checking.
///
/// - **`PendingEvent`** (enum): One variant per declared event channel. Each
///   variant holds `(SenderId, ReceiverId, Payload)`.
///
/// - **`PendingCreate`** (enum): One variant per declared SM type. Each variant
///   holds `(Id, HandlerStruct)`.
///
/// ## Effect buffering
///
/// All changes made through the context are queued and applied after the handler
/// returns. Creates are applied first (so edges can reference new SMs), then
/// signals, edges, events, and finally self-destruct. The router then cascades
/// any resulting changes within the same round.
///
/// ## Lifecycle
///
/// - **`initialize`** is called once, immediately after the SM is created (both
///   for external `router.create_*()` calls and internal `ctx.create_*()` calls).
///   Use it to set initial signals, edges, or spawn child SMs. Has a default
///   no-op implementation.
///
/// - **`handle`** is called each time an aggregated input or event is delivered.
pub trait SmHandler<Ctx> {
    type Input;
    fn handle(&mut self, input: Self::Input, ctx: &mut Ctx);
    fn initialize(&mut self, _ctx: &mut Ctx) {}
}

/// Built-in aggregator that collects all signal values into a `Vec`.
///
/// Works with any single-source `(Id, Value)` input. The ID is discarded; only
/// values are collected. SMs enforce cardinality invariants themselves — for
/// example, a spec input expects `len 0..1` and can use `.into_iter().next()`
/// to extract the single value.
pub struct ListAggregator<Id, V>(std::marker::PhantomData<(Id, V)>);

impl<Id, V> ListAggregator<Id, V> {
    pub fn new() -> Self {
        ListAggregator(std::marker::PhantomData)
    }
}

impl<Id, V> Default for ListAggregator<Id, V> {
    fn default() -> Self {
        Self::new()
    }
}

// Allow the crate to refer to itself by extern name, so that the proc-macro
// generated code (`::distvirt_sm_router::trace::...`) resolves both from within
// this crate and from external crates.
extern crate self as distvirt_sm_router;

pub use distvirt_sm_router_macros::router;

impl<Id, V: Clone> Aggregator for ListAggregator<Id, V> {
    type Input = (Id, V);
    type Output = Vec<V>;

    fn aggregate(&self, inputs: &[(Id, V)]) -> Vec<V> {
        inputs.iter().map(|(_, v)| v.clone()).collect()
    }
}

pub mod model_check;
pub mod trace;

/// Phase state machine for manual (step-by-step) propagation.
///
/// Tracks which sub-round the router is currently in:
/// - `Idle`: no manual propagation in progress.
/// - `Inputs(n)`: delivering dirty inputs; `n` outstanding.
/// - `Events(n)`: delivering events; `n` outstanding.
#[derive(Clone, Debug)]
pub enum ManualPhase {
    Idle,
    Inputs(usize),
    Events(usize),
}

/// Trait for delivery items that can be grouped by target SM.
pub trait Delivery {
    /// Returns the SM index for grouping. Items with the same key target
    /// the same SM within the current sub-round.
    fn group_key(&self) -> usize;
}

/// Step-by-step propagation controller.
///
/// Holds sorted deliveries and yields them one SM group at a time.
/// Created by `router.begin_manual_propagate()`.
pub struct ManualPropagate<D> {
    /// Sorted by group_key (ascending). We pop from the back.
    deliveries: Vec<D>,
}

impl<D: Delivery> ManualPropagate<D> {
    pub fn new(mut deliveries: Vec<D>) -> Self {
        // Sort ascending by sm_index — we pop groups from the back
        deliveries.sort_by_key(|d| d.group_key());
        ManualPropagate { deliveries }
    }

    /// Returns all deliveries for one SM group, or None if empty.
    /// Groups are returned in reverse order (last sorted group first),
    /// but since SM groups are independent, order doesn't matter.
    pub fn next_group(&mut self) -> Option<Vec<D>> {
        if self.deliveries.is_empty() {
            return None;
        }
        let last_key = self.deliveries.last().unwrap().group_key();
        let group_start = self
            .deliveries
            .iter()
            .rposition(|d| d.group_key() != last_key)
            .map(|i| i + 1)
            .unwrap_or(0);
        Some(self.deliveries.split_off(group_start))
    }

    /// Number of remaining deliveries across all groups.
    pub fn remaining(&self) -> usize {
        self.deliveries.len()
    }
}

/// Trait implemented by the generated `NodeKind` enum.
///
/// `NodeKind` has one variant per declared SM and port type. Auto-ID variants
/// come first (in declaration order), followed by manual-ID variants. The
/// `index()` method returns the discriminant, which is used by [`IdAllocator`]
/// to maintain per-kind counters.
pub trait IdKind: Copy + Clone + 'static {
    /// Number of node kinds that use auto-generated IDs.
    const AUTO_COUNT: usize;
    /// Total number of node kinds (auto + manual).
    const COUNT: usize;
    /// Discriminant index for this kind.
    fn index(self) -> usize;
    /// Human-readable name (e.g. `"Workload"`).
    fn name(self) -> &'static str;
    /// Whether this kind uses auto-generated IDs.
    fn is_auto(self) -> bool {
        self.index() < Self::AUTO_COUNT
    }
}

/// Swappable ID allocation strategy for auto-ID node types.
///
/// The router and [`CtxConcrete`] are generic over this trait. The default
/// implementation is [`SequentialIds`]. Custom allocators can be used for
/// model checking (e.g. per-creator-instance counters to avoid false state
/// divergence from ID ordering).
///
/// To use `CtxConcrete` outside the router (for isolated SM testing or model
/// checking), supply any `IdAllocator` implementation:
///
/// ```rust,ignore
/// let mut alloc = SequentialIds::<NodeKind>::new();
/// let mut ctx = WorkloadCtxConcrete::new(workload_id, &mut alloc);
/// sm.handle(input, &mut ctx);
/// let effects = ctx.into_effects();
/// // inspect effects...
/// ```
pub trait IdAllocator<K: IdKind>: Clone {
    /// Snapshot representation for serialization.
    type Snapshot: Clone;
    /// Allocate a new u64 for the given auto-ID node kind.
    /// `creator` is `Some((kind, raw_id))` when called from an SM handler.
    fn alloc(&mut self, kind: K, creator: Option<(K, u64)>) -> u64;
    /// Export state for snapshotting.
    fn snapshot(&self) -> Self::Snapshot;
    /// Reconstruct from a snapshot.
    fn from_snapshot(snapshot: &Self::Snapshot) -> Self;
}

/// Default allocator: simple sequential counters per auto-ID node kind.
#[derive(Clone, Debug)]
pub struct SequentialIds<K: IdKind> {
    counters: Vec<u64>,
    _kind: std::marker::PhantomData<K>,
}

impl<K: IdKind> SequentialIds<K> {
    pub fn new() -> Self {
        Self {
            counters: vec![0; K::AUTO_COUNT],
            _kind: std::marker::PhantomData,
        }
    }
}

impl<K: IdKind> Default for SequentialIds<K> {
    fn default() -> Self {
        Self::new()
    }
}

impl<K: IdKind> IdAllocator<K> for SequentialIds<K> {
    type Snapshot = Vec<u64>;
    fn alloc(&mut self, kind: K, _creator: Option<(K, u64)>) -> u64 {
        let idx = kind.index();
        let id = self.counters[idx];
        self.counters[idx] += 1;
        id
    }
    fn snapshot(&self) -> Vec<u64> {
        self.counters.clone()
    }
    fn from_snapshot(snapshot: &Vec<u64>) -> Self {
        Self {
            counters: snapshot.clone(),
            _kind: std::marker::PhantomData,
        }
    }
}

#[cfg(test)]
mod tests;
