//! # Signal Router
//!
//! A framework for coordinating state machines (SMs) that communicate through
//! typed signals, structural edges, and discrete events. The router maintains
//! the connectivity graph and mechanically propagates signal changes — SMs
//! contain only domain logic, never relationship bookkeeping.
//!
//! See [`docs/design/signal-router.md`] for full design rationale.
//!
//! ## Core concepts
//!
//! - **SM (State Machine):** An instance with identity, internal state, output
//!   signals, and a handler for incoming inputs. SMs contain domain logic only.
//!
//! - **Port:** An external boundary point (worker connection, management layer)
//!   that produces signals and sends events but has no state machine lifecycle.
//!
//! - **Signal:** A persistent current-value that an SM or port instance produces.
//!   Declared per type, keyed by `(instance_id, signal_type)`. The router uses
//!   `PartialEq` to detect changes — setting a signal to its current value is a
//!   no-op.
//!
//! - **Edge:** A unidirectional typed relationship between instances. Edges don't
//!   carry data directly — they define structure. Signals flow through edges as
//!   determined by aggregated input declarations.
//!
//! - **Aggregated Input:** A declared input on a consuming SM that specifies
//!   `(EdgeType, Signal)` source pairs and an [`Aggregator`] to combine them.
//!   The router re-aggregates whenever edges or source signals change.
//!
//! - **Event:** A one-shot discrete message between instances that have an edge
//!   relationship (checked in either direction). Not aggregated.
//!
//! Signals can have **invariants** — expressions that must hold at quiescence.
//! Violations are reported via the [tracing infrastructure](trace). See [`trace`]
//! module docs.
//!
//! ## Quick example
//!
//! ```rust,ignore
//! use distvirt_sm_router::{router, Aggregator, SmHandler, ListAggregator};
//!
//! // 1. Define ID types
//! #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
//! struct ServiceId(u64);
//!
//! #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
//! struct WorkloadId(u64);
//!
//! // 2. Define a custom aggregator
//! #[derive(Default)]
//! struct DemandAggregator;
//!
//! impl Aggregator for DemandAggregator {
//!     type Input = (ServiceId, bool);
//!     type Output = u32;
//!
//!     fn aggregate(&self, inputs: &[(ServiceId, bool)]) -> u32 {
//!         inputs.iter().filter(|(_, demand)| *demand).count() as u32
//!     }
//! }
//!
//! // 3. Declare the topology
//! router! {
//!     state_machines {
//!         Service(ServiceId, ServiceSm),
//!         Workload(WorkloadId, WorkloadSm),
//!     }
//!     ports {}
//!     signals {
//!         Service::Demand(bool),
//!     }
//!     edges {
//!         ServiceToWorkload: Service -> Workload,
//!     }
//!     events {}
//!     inputs {
//!         Workload::DemandInput {
//!             sources: [(ServiceToWorkload, Service::Demand)],
//!             aggregator: DemandAggregator,
//!         },
//!     }
//!     invariants {
//!         Service::Demand(*value),  // services should have demand at quiescence
//!     }
//! }
//!
//! // 4. Implement SM handlers (types are generated by the macro)
//! struct ServiceSm;
//!
//! impl SmHandler for ServiceSm {
//!     type Input = ServiceInput;   // generated enum (empty here — no inputs declared)
//!     type Ctx = ServiceCtx;       // generated context struct
//!
//!     fn handle(&mut self, input: Self::Input, ctx: &mut Self::Ctx) {
//!         // handle inputs...
//!     }
//! }
//!
//! struct WorkloadSm {
//!     demand_count: u32,
//! }
//!
//! impl SmHandler for WorkloadSm {
//!     type Input = WorkloadInput;  // generated: has DemandInput(u32) variant
//!     type Ctx = WorkloadCtx;
//!
//!     fn handle(&mut self, input: Self::Input, ctx: &mut Self::Ctx) {
//!         match input {
//!             WorkloadInput::DemandInput(count) => {
//!                 self.demand_count = count;
//!             }
//!         }
//!     }
//! }
//!
//! // 5. Drive the router
//! let mut router = Router::new(16);
//!
//! let s1 = ServiceId(1);
//! let w1 = WorkloadId(1);
//!
//! router.create_service(s1, ServiceSm);
//! router.create_workload(w1, WorkloadSm { demand_count: 0 });
//!
//! // Establish edge and set signal
//! router.set_service_to_workload_edges(s1, vec![w1]);
//! router.set_service_demand(s1, true);
//!
//! // Propagate resolves all cascading effects
//! router.propagate();
//! // WorkloadSm received DemandInput(1)
//! ```
//!
//! ## Propagation model
//!
//! Signal propagation is organized into **rounds**. When `propagate()` is called,
//! all cascading effects resolve before it returns:
//!
//! 1. A signal change or edge change marks affected inputs as dirty
//! 2. The router re-aggregates each dirty input and delivers it to the SM handler
//!    (only if the aggregated value actually changed — `PartialEq` comparison)
//! 3. The handler may update signals and edges via its context, which feeds back
//!    into step 1
//! 4. The round ends when no more updates propagate
//!
//! A configurable depth limit (passed to `Router::new()`) prevents infinite loops.
//! The router warns at `limit - 1` and panics at `limit`.

/// Reduces N signal values (from N incoming edges) into one aggregated input value.
///
/// The `Input` type is determined by the topology declaration:
/// - **Single-source inputs:** `(SourceId, SignalValue)` tuple
/// - **Multi-source inputs:** a generated enum with one variant per `(EdgeType, Signal)`
///   source pair, e.g. `enum DemandInputSource { ServiceDemand(ServiceId, bool), ... }`
///
/// Aggregators **must** handle the empty-input case (zero edges) — this produces the
/// "no data" baseline (e.g., `0`, empty vec). There is no concept of "uninitialized".
///
/// # Example
///
/// ```rust,ignore
/// #[derive(Default)]
/// struct CountTrueAggregator;
///
/// impl Aggregator for CountTrueAggregator {
///     type Input = (ServiceId, bool);
///     type Output = u32;
///
///     fn aggregate(&self, inputs: &[(ServiceId, bool)]) -> u32 {
///         inputs.iter().filter(|(_, v)| *v).count() as u32
///     }
/// }
/// ```
pub trait Aggregator {
    type Input;
    type Output;
    fn aggregate(&self, inputs: &[Self::Input]) -> Self::Output;
}

/// Handler trait for state machines. Each SM type implements this on its struct.
///
/// The associated types are generated per-SM-type by the [`router!`] macro:
///
/// - **`Input`**: An enum with one variant per aggregated input declared for this SM,
///   plus one variant per event channel where this SM is the receiver. This gives
///   exhaustive match coverage — adding a new input or event is a compile error until
///   handled.
///
/// - **`Ctx`**: A context struct scoped to this SM type. It exposes methods to:
///   - `ctx.id()` — get this instance's ID
///   - `ctx.set_{signal_name}(value)` — update an output signal
///   - `ctx.set_{edge_name}_edges(targets)` — update outgoing edges
///   - `ctx.send_{event_name}(target, payload)` — send a discrete event
///   - `ctx.create_{sm_name}(sm)` — create a new SM instance (returns ID for auto-ID types)
///   - `ctx.destroy_{sm_name}(id)` — destroy an SM instance
///
/// All changes are queued and applied after the handler returns. Creates are
/// applied first (so edges can reference new SMs), then signals, edges, events,
/// and finally destroys. The router then cascades any resulting changes within
/// the same round.
pub trait SmHandler {
    type Input;
    type Ctx;
    fn handle(&mut self, input: Self::Input, ctx: &mut Self::Ctx);
}

/// Built-in aggregator that collects all signal values into a `Vec`.
///
/// Works with any single-source `(Id, Value)` input. The ID is discarded; only
/// values are collected. SMs enforce cardinality invariants themselves — for
/// example, a spec input expects `len 0..1` and can use `.into_iter().next()`
/// to extract the single value.
pub struct ListAggregator<Id, V>(std::marker::PhantomData<(Id, V)>);

impl<Id, V> ListAggregator<Id, V> {
    pub fn new() -> Self {
        ListAggregator(std::marker::PhantomData)
    }
}

impl<Id, V> Default for ListAggregator<Id, V> {
    fn default() -> Self {
        Self::new()
    }
}

pub use distvirt_sm_router_macros::router;

impl<Id, V: Clone> Aggregator for ListAggregator<Id, V> {
    type Input = (Id, V);
    type Output = Vec<V>;

    fn aggregate(&self, inputs: &[(Id, V)]) -> Vec<V> {
        inputs.iter().map(|(_, v)| v.clone()).collect()
    }
}

pub mod model_check;
pub mod trace;

#[cfg(test)]
mod tests;
