use std::collections::{HashMap, HashSet, VecDeque};

use crate::{Aggregator, ListAggregator, SmHandler};

// ===========================================================================
// Test Topology — hand-written "generated" code
//
// SM types: AlphaSm, BetaSm
// Port types: GammaPort
//
// Signals:
//   AlphaSm::Demand(bool)
//   BetaSm::Status(u32)
//   GammaPort::Value(u32)
//
// Edges:
//   AlphaToBeta: AlphaSm -> BetaSm
//   BetaToAlpha: BetaSm -> AlphaSm
//   GammaToBeta: GammaPort -> BetaSm
//
// Inputs:
//   BetaSm::DemandInput:
//     sources: [(AlphaToBeta, AlphaSm::Demand)]
//     aggregator: CountTrueAggregator -> u32
//
//   BetaSm::ConfigInput:
//     sources: [(GammaToBeta, GammaPort::Value)]
//     aggregator: ListAggregator -> Vec<u32>
//
//   AlphaSm::StatusInput:
//     sources: [(BetaToAlpha, BetaSm::Status)]
//     aggregator: ListAggregator -> Vec<u32>
// ===========================================================================

// ---- ID types ----

#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
struct AlphaId(u64);

#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
struct BetaId(u64);

#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
struct GammaId(u64);

// ---- SM input enums (one per SM type) ----
// MACRO NOTE: Generated by the macro. One variant per aggregated input,
// plus one variant per received event channel.

#[derive(Debug, PartialEq)]
enum AlphaSmInput {
    StatusInput(Vec<u32>),
}

#[derive(Debug, PartialEq)]
enum BetaSmInput {
    DemandInput(u32),
    ConfigInput(Vec<u32>),
}

// ---- SM handler contexts (one per SM type) ----
// MACRO NOTE: Generated by the macro. One Ctx struct per SM type with
// Option fields for each signal and edge set the SM can produce.
// The propagation loop creates a fresh Ctx, passes it to the handler,
// then applies effects via apply_*_effects().

struct AlphaSmCtx {
    #[allow(dead_code)]
    id: AlphaId,
    set_demand: Option<bool>,
    set_alpha_to_beta: Option<Vec<BetaId>>,
}

impl AlphaSmCtx {
    fn new(id: AlphaId) -> Self {
        AlphaSmCtx {
            id,
            set_demand: None,
            set_alpha_to_beta: None,
        }
    }

    #[allow(dead_code)]
    pub fn id(&self) -> AlphaId {
        self.id
    }

    pub fn set_demand(&mut self, value: bool) {
        self.set_demand = Some(value);
    }

    #[allow(dead_code)]
    pub fn set_alpha_to_beta_edges(&mut self, targets: Vec<BetaId>) {
        self.set_alpha_to_beta = Some(targets);
    }
}

struct BetaSmCtx {
    #[allow(dead_code)]
    id: BetaId,
    set_status: Option<u32>,
    set_beta_to_alpha: Option<Vec<AlphaId>>,
}

impl BetaSmCtx {
    fn new(id: BetaId) -> Self {
        BetaSmCtx {
            id,
            set_status: None,
            set_beta_to_alpha: None,
        }
    }

    #[allow(dead_code)]
    pub fn id(&self) -> BetaId {
        self.id
    }

    pub fn set_status(&mut self, value: u32) {
        self.set_status = Some(value);
    }

    pub fn set_beta_to_alpha_edges(&mut self, targets: Vec<AlphaId>) {
        self.set_beta_to_alpha = Some(targets);
    }
}

// ---- SM trait impls ----
// Users implement SmHandler on their SM structs. The Input and Ctx
// associated types are generated per-SM-type by the macro.
// The SM struct holds whatever state the SM needs.

// AlphaSm: test SM that records deliveries for assertions.
struct AlphaSm {
    deliveries: Vec<AlphaSmInput>,
    on_handle: Option<Box<dyn FnMut(&AlphaSmInput, &mut AlphaSmCtx)>>,
}

impl AlphaSm {
    fn new() -> Self {
        AlphaSm {
            deliveries: Vec::new(),
            on_handle: None,
        }
    }
}

impl SmHandler for AlphaSm {
    type Input = AlphaSmInput;
    type Ctx = AlphaSmCtx;

    fn handle(&mut self, input: Self::Input, ctx: &mut Self::Ctx) {
        if let Some(ref mut cb) = self.on_handle {
            cb(&input, ctx);
        }
        self.deliveries.push(input);
    }
}

// BetaSm: test SM that records deliveries for assertions.
struct BetaSm {
    deliveries: Vec<BetaSmInput>,
    on_handle: Option<Box<dyn FnMut(&BetaSmInput, &mut BetaSmCtx)>>,
}

impl BetaSm {
    fn new() -> Self {
        BetaSm {
            deliveries: Vec::new(),
            on_handle: None,
        }
    }
}

impl SmHandler for BetaSm {
    type Input = BetaSmInput;
    type Ctx = BetaSmCtx;

    fn handle(&mut self, input: Self::Input, ctx: &mut Self::Ctx) {
        if let Some(ref mut cb) = self.on_handle {
            cb(&input, ctx);
        }
        self.deliveries.push(input);
    }
}

// ---- Aggregators ----

struct CountTrueAggregator;

impl Aggregator for CountTrueAggregator {
    type Input = (AlphaId, bool);
    type Output = u32;

    fn aggregate(&self, inputs: &[(AlphaId, bool)]) -> u32 {
        inputs.iter().filter(|(_, demand)| *demand).count() as u32
    }
}

type AlphaStatusAggregator = ListAggregator<BetaId, u32>;
type BetaConfigAggregator = ListAggregator<GammaId, u32>;

// ---- Dirty queue ----

#[derive(Clone, Eq, PartialEq, Hash, Debug)]
enum DirtyInput {
    BetaDemand(BetaId),
    BetaConfig(BetaId),
    AlphaStatus(AlphaId),
}

// ---- Router ----
// MACRO NOTE: The macro generates this entire struct. SM types are stored
// as HashMap<Id, SmStruct> — the router owns SM instances directly.
// Port types have no user-defined state, so they remain as HashSets.

struct Router {
    // SM instance storage (owns SM structs)
    alpha_instances: HashMap<AlphaId, AlphaSm>,
    beta_instances: HashMap<BetaId, BetaSm>,

    // Port instance registry (no user state)
    gamma_instances: HashSet<GammaId>,

    // Signals (initialized to Default::default() at instance creation)
    alpha_demand: HashMap<AlphaId, bool>,
    beta_status: HashMap<BetaId, u32>,
    gamma_value: HashMap<GammaId, u32>,

    // Edges: AlphaToBeta (AlphaSm -> BetaSm)
    alpha_to_beta_fwd: HashMap<AlphaId, Vec<BetaId>>,
    alpha_to_beta_rev: HashMap<BetaId, HashSet<AlphaId>>,

    // Edges: BetaToAlpha (BetaSm -> AlphaSm)
    beta_to_alpha_fwd: HashMap<BetaId, Vec<AlphaId>>,
    beta_to_alpha_rev: HashMap<AlphaId, HashSet<BetaId>>,

    // Edges: GammaToBeta (GammaPort -> BetaSm)
    gamma_to_beta_fwd: HashMap<GammaId, Vec<BetaId>>,
    gamma_to_beta_rev: HashMap<BetaId, HashSet<GammaId>>,

    // Last delivered aggregation results (for change detection)
    last_beta_demand: HashMap<BetaId, u32>,
    last_beta_config: HashMap<BetaId, Vec<u32>>,
    last_alpha_status: HashMap<AlphaId, Vec<u32>>,

    // Propagation
    dirty: VecDeque<DirtyInput>,
    depth_limit: usize,
}

impl Router {
    fn new(depth_limit: usize) -> Self {
        Router {
            alpha_instances: HashMap::new(),
            beta_instances: HashMap::new(),
            gamma_instances: HashSet::new(),
            alpha_demand: HashMap::new(),
            beta_status: HashMap::new(),
            gamma_value: HashMap::new(),
            alpha_to_beta_fwd: HashMap::new(),
            alpha_to_beta_rev: HashMap::new(),
            beta_to_alpha_fwd: HashMap::new(),
            beta_to_alpha_rev: HashMap::new(),
            gamma_to_beta_fwd: HashMap::new(),
            gamma_to_beta_rev: HashMap::new(),
            last_beta_demand: HashMap::new(),
            last_beta_config: HashMap::new(),
            last_alpha_status: HashMap::new(),
            dirty: VecDeque::new(),
            depth_limit,
        }
    }

    // ---- Instance creation ----
    // SM creation takes the user's SM struct and stores it in the router.
    // Signals are initialized to Default::default(). No eager delivery occurs
    // (the SM's first delivery happens when edges are established).

    fn create_alpha(&mut self, id: AlphaId, sm: AlphaSm) {
        self.alpha_instances.insert(id, sm);
        self.alpha_demand.insert(id, Default::default());
    }

    fn create_beta(&mut self, id: BetaId, sm: BetaSm) {
        self.beta_instances.insert(id, sm);
        self.beta_status.insert(id, Default::default());
    }

    fn create_gamma(&mut self, id: GammaId) {
        self.gamma_instances.insert(id);
        self.gamma_value.insert(id, Default::default());
    }

    // ---- Instance destruction ----

    /// Destroy an AlphaSm instance. Returns the SM struct if it existed.
    /// - Removes outgoing edges (AlphaToBeta), triggers re-aggregation on targets.
    /// - Leaves incoming edges (BetaToAlpha pointing here) as dangling.
    /// - Removes signal storage and last-delivered results.
    fn destroy_alpha(&mut self, id: AlphaId) -> Option<AlphaSm> {
        let sm = self.alpha_instances.remove(&id);
        self.alpha_demand.remove(&id);
        self.last_alpha_status.remove(&id);
        // Remove outgoing edges
        self.set_alpha_to_beta_edges(id, vec![]);
        sm
    }

    /// Destroy a BetaSm instance. Returns the SM struct if it existed.
    /// - Removes outgoing edges (BetaToAlpha), triggers re-aggregation on targets.
    /// - Leaves incoming edges (AlphaToBeta, GammaToBeta pointing here) as dangling.
    /// - Removes signal storage and last-delivered results.
    fn destroy_beta(&mut self, id: BetaId) -> Option<BetaSm> {
        let sm = self.beta_instances.remove(&id);
        self.beta_status.remove(&id);
        self.last_beta_demand.remove(&id);
        self.last_beta_config.remove(&id);
        // Remove outgoing edges
        self.set_beta_to_alpha_edges(id, vec![]);
        sm
    }

    /// Remove a GammaPort instance.
    /// Ports get full cleanup — all edges from/to the port are removed.
    fn remove_gamma(&mut self, id: GammaId) {
        self.gamma_instances.remove(&id);
        self.gamma_value.remove(&id);
        // Remove outgoing edges (GammaToBeta)
        self.set_gamma_to_beta_edges(id, vec![]);
        // GammaPort has no incoming edge types in this topology,
        // but if it did, we would remove them here too.
    }

    // ---- External signal setters ----
    // These do change detection and enqueue dirty entries, but don't propagate.

    fn set_alpha_demand(&mut self, id: AlphaId, value: bool) {
        if self.alpha_demand.get(&id) == Some(&value) {
            return;
        }
        self.alpha_demand.insert(id, value);
        // AlphaSm::Demand feeds BetaSm::DemandInput through AlphaToBeta
        if let Some(targets) = self.alpha_to_beta_fwd.get(&id) {
            for &beta_id in targets {
                self.dirty.push_back(DirtyInput::BetaDemand(beta_id));
            }
        }
    }

    fn set_beta_status(&mut self, id: BetaId, value: u32) {
        if self.beta_status.get(&id) == Some(&value) {
            return;
        }
        self.beta_status.insert(id, value);
        // BetaSm::Status feeds AlphaSm::StatusInput through BetaToAlpha
        if let Some(targets) = self.beta_to_alpha_fwd.get(&id) {
            for &alpha_id in targets {
                self.dirty.push_back(DirtyInput::AlphaStatus(alpha_id));
            }
        }
    }

    fn set_gamma_value(&mut self, id: GammaId, value: u32) {
        if self.gamma_value.get(&id) == Some(&value) {
            return;
        }
        self.gamma_value.insert(id, value);
        // GammaPort::Value feeds BetaSm::ConfigInput through GammaToBeta
        if let Some(targets) = self.gamma_to_beta_fwd.get(&id) {
            for &beta_id in targets {
                self.dirty.push_back(DirtyInput::BetaConfig(beta_id));
            }
        }
    }

    // ---- External edge setters ----

    fn set_alpha_to_beta_edges(&mut self, source: AlphaId, new_targets: Vec<BetaId>) {
        let old_set: HashSet<BetaId> = self
            .alpha_to_beta_fwd
            .get(&source)
            .map(|v| v.iter().copied().collect())
            .unwrap_or_default();
        let new_set: HashSet<BetaId> = new_targets.iter().copied().collect();

        let removed: Vec<BetaId> = old_set.difference(&new_set).copied().collect();
        let added: Vec<BetaId> = new_set.difference(&old_set).copied().collect();

        // No-op if edge set unchanged
        if removed.is_empty() && added.is_empty() {
            return;
        }

        // Update forward index
        if new_targets.is_empty() {
            self.alpha_to_beta_fwd.remove(&source);
        } else {
            self.alpha_to_beta_fwd.insert(source, new_targets);
        }

        // Update reverse index
        for &tgt in &removed {
            if let Some(sources) = self.alpha_to_beta_rev.get_mut(&tgt) {
                sources.remove(&source);
                if sources.is_empty() {
                    self.alpha_to_beta_rev.remove(&tgt);
                }
            }
        }
        for &tgt in &added {
            self.alpha_to_beta_rev
                .entry(tgt)
                .or_default()
                .insert(source);
        }

        // AlphaToBeta feeds BetaSm::DemandInput — enqueue affected targets
        for tgt in removed.iter().chain(added.iter()) {
            self.dirty.push_back(DirtyInput::BetaDemand(*tgt));
        }
    }

    fn set_beta_to_alpha_edges(&mut self, source: BetaId, new_targets: Vec<AlphaId>) {
        let old_set: HashSet<AlphaId> = self
            .beta_to_alpha_fwd
            .get(&source)
            .map(|v| v.iter().copied().collect())
            .unwrap_or_default();
        let new_set: HashSet<AlphaId> = new_targets.iter().copied().collect();

        let removed: Vec<AlphaId> = old_set.difference(&new_set).copied().collect();
        let added: Vec<AlphaId> = new_set.difference(&old_set).copied().collect();

        // No-op if edge set unchanged
        if removed.is_empty() && added.is_empty() {
            return;
        }

        if new_targets.is_empty() {
            self.beta_to_alpha_fwd.remove(&source);
        } else {
            self.beta_to_alpha_fwd.insert(source, new_targets);
        }

        for &tgt in &removed {
            if let Some(sources) = self.beta_to_alpha_rev.get_mut(&tgt) {
                sources.remove(&source);
                if sources.is_empty() {
                    self.beta_to_alpha_rev.remove(&tgt);
                }
            }
        }
        for &tgt in &added {
            self.beta_to_alpha_rev
                .entry(tgt)
                .or_default()
                .insert(source);
        }

        // BetaToAlpha feeds AlphaSm::StatusInput — enqueue affected targets
        for tgt in removed.iter().chain(added.iter()) {
            self.dirty.push_back(DirtyInput::AlphaStatus(*tgt));
        }
    }

    fn set_gamma_to_beta_edges(&mut self, source: GammaId, new_targets: Vec<BetaId>) {
        let old_set: HashSet<BetaId> = self
            .gamma_to_beta_fwd
            .get(&source)
            .map(|v| v.iter().copied().collect())
            .unwrap_or_default();
        let new_set: HashSet<BetaId> = new_targets.iter().copied().collect();

        let removed: Vec<BetaId> = old_set.difference(&new_set).copied().collect();
        let added: Vec<BetaId> = new_set.difference(&old_set).copied().collect();

        if removed.is_empty() && added.is_empty() {
            return;
        }

        if new_targets.is_empty() {
            self.gamma_to_beta_fwd.remove(&source);
        } else {
            self.gamma_to_beta_fwd.insert(source, new_targets);
        }

        for &tgt in &removed {
            if let Some(sources) = self.gamma_to_beta_rev.get_mut(&tgt) {
                sources.remove(&source);
                if sources.is_empty() {
                    self.gamma_to_beta_rev.remove(&tgt);
                }
            }
        }
        for &tgt in &added {
            self.gamma_to_beta_rev
                .entry(tgt)
                .or_default()
                .insert(source);
        }

        // GammaToBeta feeds BetaSm::ConfigInput — enqueue affected targets
        for tgt in removed.iter().chain(added.iter()) {
            self.dirty.push_back(DirtyInput::BetaConfig(*tgt));
        }
    }

    // ---- Aggregation ----

    fn aggregate_beta_demand(&self, beta_id: BetaId) -> u32 {
        let mut inputs = Vec::new();
        if let Some(sources) = self.alpha_to_beta_rev.get(&beta_id) {
            for &alpha_id in sources {
                if let Some(&demand) = self.alpha_demand.get(&alpha_id) {
                    inputs.push((alpha_id, demand));
                }
            }
        }
        CountTrueAggregator.aggregate(&inputs)
    }

    fn aggregate_beta_config(&self, beta_id: BetaId) -> Vec<u32> {
        let mut inputs = Vec::new();
        if let Some(sources) = self.gamma_to_beta_rev.get(&beta_id) {
            for &gamma_id in sources {
                if let Some(&value) = self.gamma_value.get(&gamma_id) {
                    inputs.push((gamma_id, value));
                }
            }
        }
        BetaConfigAggregator::new().aggregate(&inputs)
    }

    fn aggregate_alpha_status(&self, alpha_id: AlphaId) -> Vec<u32> {
        let mut inputs = Vec::new();
        if let Some(sources) = self.beta_to_alpha_rev.get(&alpha_id) {
            for &beta_id in sources {
                if let Some(&status) = self.beta_status.get(&beta_id) {
                    inputs.push((beta_id, status));
                }
            }
        }
        AlphaStatusAggregator::new().aggregate(&inputs)
    }

    // ---- Effects application ----

    fn apply_alpha_effects(&mut self, id: AlphaId, ctx: AlphaSmCtx) {
        if let Some(value) = ctx.set_demand {
            self.set_alpha_demand(id, value);
        }
        if let Some(targets) = ctx.set_alpha_to_beta {
            self.set_alpha_to_beta_edges(id, targets);
        }
    }

    fn apply_beta_effects(&mut self, id: BetaId, ctx: BetaSmCtx) {
        if let Some(value) = ctx.set_status {
            self.set_beta_status(id, value);
        }
        if let Some(targets) = ctx.set_beta_to_alpha {
            self.set_beta_to_alpha_edges(id, targets);
        }
    }

    // ---- Propagation loop ----
    // Dispatches directly to owned SM structs via SmHandler trait.
    // Uses take-call-reinsert pattern to avoid borrow conflicts:
    // the SM is temporarily removed from the HashMap during handler
    // invocation so we can mutate both the SM and the router.

    fn propagate(&mut self) {
        let mut depth = 0;

        while !self.dirty.is_empty() {
            depth += 1;
            if depth == self.depth_limit {
                panic!(
                    "Signal router depth limit ({}) exceeded",
                    self.depth_limit
                );
            }
            if depth == self.depth_limit - 1 {
                eprintln!(
                    "WARNING: Signal router approaching depth limit ({}/{})",
                    depth, self.depth_limit
                );
            }

            // Drain current wave, dedup
            let wave: Vec<DirtyInput> = self.dirty.drain(..).collect();
            let mut seen = HashSet::new();

            for entry in wave {
                if !seen.insert(entry.clone()) {
                    continue;
                }

                match entry {
                    DirtyInput::BetaDemand(beta_id) => {
                        if !self.beta_instances.contains_key(&beta_id) {
                            continue;
                        }
                        let result = self.aggregate_beta_demand(beta_id);
                        // Skip delivery if aggregated result unchanged
                        if self.last_beta_demand.get(&beta_id) == Some(&result) {
                            continue;
                        }
                        self.last_beta_demand.insert(beta_id, result.clone());

                        // Take SM out, call handler, reinsert
                        let mut sm = self.beta_instances.remove(&beta_id).unwrap();
                        let mut ctx = BetaSmCtx::new(beta_id);
                        sm.handle(BetaSmInput::DemandInput(result), &mut ctx);
                        self.beta_instances.insert(beta_id, sm);

                        self.apply_beta_effects(beta_id, ctx);
                    }
                    DirtyInput::BetaConfig(beta_id) => {
                        if !self.beta_instances.contains_key(&beta_id) {
                            continue;
                        }
                        let result = self.aggregate_beta_config(beta_id);
                        if self.last_beta_config.get(&beta_id) == Some(&result) {
                            continue;
                        }
                        self.last_beta_config.insert(beta_id, result.clone());

                        let mut sm = self.beta_instances.remove(&beta_id).unwrap();
                        let mut ctx = BetaSmCtx::new(beta_id);
                        sm.handle(BetaSmInput::ConfigInput(result), &mut ctx);
                        self.beta_instances.insert(beta_id, sm);

                        self.apply_beta_effects(beta_id, ctx);
                    }
                    DirtyInput::AlphaStatus(alpha_id) => {
                        if !self.alpha_instances.contains_key(&alpha_id) {
                            continue;
                        }
                        let result = self.aggregate_alpha_status(alpha_id);
                        if self.last_alpha_status.get(&alpha_id) == Some(&result) {
                            continue;
                        }
                        self.last_alpha_status.insert(alpha_id, result.clone());

                        let mut sm = self.alpha_instances.remove(&alpha_id).unwrap();
                        let mut ctx = AlphaSmCtx::new(alpha_id);
                        sm.handle(AlphaSmInput::StatusInput(result), &mut ctx);
                        self.alpha_instances.insert(alpha_id, sm);

                        self.apply_alpha_effects(alpha_id, ctx);
                    }
                }
            }
        }
    }
}

// ===========================================================================
// Phase 1 Tests
// ===========================================================================

const A1: AlphaId = AlphaId(1);
const A2: AlphaId = AlphaId(2);
const A3: AlphaId = AlphaId(3);
const B1: BetaId = BetaId(1);
const B2: BetaId = BetaId(2);
const G1: GammaId = GammaId(1);
const G2: GammaId = GammaId(2);

#[test]
fn basic_signal_propagation() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    // Create edge A1 -> B1, propagate (B1 gets empty aggregation)
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(b1.deliveries.len(), 1);
    assert_eq!(b1.deliveries[0], BetaSmInput::DemandInput(0));

    // Set signal on A1
    router.set_alpha_demand(A1, true);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(b1.deliveries.len(), 2);
    assert_eq!(b1.deliveries[1], BetaSmInput::DemandInput(1));
}

#[test]
fn change_detection_no_delivery_on_same_value() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_alpha_demand(A1, true);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(b1.deliveries.len(), 1);

    // Set same value again — no propagation
    router.set_alpha_demand(A1, true);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(b1.deliveries.len(), 1); // still 1, no new delivery
}

#[test]
fn multi_edge_aggregation() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_alpha(A2, AlphaSm::new());
    router.create_alpha(A3, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    // Three sources -> one target
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_alpha_to_beta_edges(A2, vec![B1]);
    router.set_alpha_to_beta_edges(A3, vec![B1]);
    router.propagate();

    // Set signals: A1=true, A2=false, A3=true
    router.set_alpha_demand(A1, true);
    router.set_alpha_demand(A2, false);
    router.set_alpha_demand(A3, true);
    router.propagate();

    // B1 should receive count=2 (A1 and A3 are true)
    let b1 = router.beta_instances.get(&B1).unwrap();
    let last = b1.deliveries.last().unwrap();
    assert_eq!(*last, BetaSmInput::DemandInput(2));
}

#[test]
fn cascading_signal_to_edge_to_signal() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());

    // When B1 receives DemandInput, it creates BetaToAlpha edge back to A1
    // and sets Status signal, which cascades to A1's StatusInput.
    let mut b1 = BetaSm::new();
    b1.on_handle = Some(Box::new(|input, ctx| {
        let BetaSmInput::DemandInput(count) = input else {
            return;
        };
        if *count > 0 {
            ctx.set_beta_to_alpha_edges(vec![A1]);
            ctx.set_status(42);
        }
    }));
    router.create_beta(B1, b1);

    // Setup: A1 --AlphaToBeta--> B1
    router.set_alpha_to_beta_edges(A1, vec![B1]);

    router.set_alpha_demand(A1, true);
    router.propagate();

    // B1 received DemandInput(1)
    let b1 = router.beta_instances.get(&B1).unwrap();
    assert!(b1
        .deliveries
        .iter()
        .any(|inp| *inp == BetaSmInput::DemandInput(1)));

    // A1 received StatusInput([42]) via cascade
    let a1 = router.alpha_instances.get(&A1).unwrap();
    assert!(a1
        .deliveries
        .iter()
        .any(|inp| *inp == AlphaSmInput::StatusInput(vec![42])));
}

#[test]
#[should_panic(expected = "depth limit")]
fn depth_limiting_panics_on_cycle() {
    let mut router = Router::new(4);

    let mut a1 = AlphaSm::new();
    let mut counter = 0u32;
    a1.on_handle = Some(Box::new(move |_input, ctx| {
        counter += 1;
        ctx.set_demand(counter % 2 == 0);
    }));
    router.create_alpha(A1, a1);

    let mut b1 = BetaSm::new();
    let mut counter2 = 0u32;
    b1.on_handle = Some(Box::new(move |_input, ctx| {
        counter2 += 1;
        ctx.set_status(counter2);
    }));
    router.create_beta(B1, b1);

    // Edges in both directions
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_beta_to_alpha_edges(B1, vec![A1]);

    // Trigger the cycle
    router.set_alpha_demand(A1, true);
    router.propagate();
}

#[test]
fn edge_removal_triggers_reaggregation() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_alpha(A2, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    // Two sources -> B1, both with demand=true
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_alpha_to_beta_edges(A2, vec![B1]);
    router.set_alpha_demand(A1, true);
    router.set_alpha_demand(A2, true);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    let last = b1.deliveries.last().unwrap();
    assert_eq!(*last, BetaSmInput::DemandInput(2));

    // Remove A2's edge
    router.set_alpha_to_beta_edges(A2, vec![]);
    router.propagate();

    // B1 re-aggregated with count=1
    let b1 = router.beta_instances.get(&B1).unwrap();
    let last = b1.deliveries.last().unwrap();
    assert_eq!(*last, BetaSmInput::DemandInput(1));
}

#[test]
fn batched_changes_single_round() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_alpha(A2, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    // Set up edges and signals in one batch, propagate once
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_alpha_to_beta_edges(A2, vec![B1]);
    router.set_alpha_demand(A1, true);
    router.set_alpha_demand(A2, true);

    router.propagate();

    // B1 should see both sources in a single delivery (deduped within wave)
    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(b1.deliveries.len(), 1);
    assert_eq!(b1.deliveries[0], BetaSmInput::DemandInput(2));
}

// ===========================================================================
// Phase 2 Tests
// ===========================================================================

#[test]
fn port_removal_cleans_edges_and_reaggregates() {
    let mut router = Router::new(16);
    router.create_beta(B1, BetaSm::new());
    router.create_gamma(G1);
    router.create_gamma(G2);

    // Two gamma ports -> B1
    router.set_gamma_to_beta_edges(G1, vec![B1]);
    router.set_gamma_to_beta_edges(G2, vec![B1]);
    router.set_gamma_value(G1, 10);
    router.set_gamma_value(G2, 20);

    router.propagate();

    // B1 should have received ConfigInput with both values
    let b1 = router.beta_instances.get(&B1).unwrap();
    let config: Vec<_> = b1
        .deliveries
        .iter()
        .filter(|inp| matches!(inp, BetaSmInput::ConfigInput(_)))
        .collect();
    assert_eq!(config.len(), 1);
    if let BetaSmInput::ConfigInput(vals) = config[0] {
        assert_eq!(vals.len(), 2);
        assert!(vals.contains(&10));
        assert!(vals.contains(&20));
    } else {
        panic!("expected ConfigInput");
    }

    // Remove G1 — B1 should re-aggregate with only G2's value
    router.remove_gamma(G1);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    let config: Vec<_> = b1
        .deliveries
        .iter()
        .filter(|inp| matches!(inp, BetaSmInput::ConfigInput(_)))
        .collect();
    assert_eq!(config.len(), 2);
    assert_eq!(*config[1], BetaSmInput::ConfigInput(vec![20]));

    // Remove G2 — B1 gets empty config
    router.remove_gamma(G2);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert!(b1
        .deliveries
        .iter()
        .any(|inp| *inp == BetaSmInput::ConfigInput(vec![])));
}

#[test]
fn dangling_edges_target_dies_source_unaffected() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    // A1 -> B1 edge
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_alpha_demand(A1, true);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(b1.deliveries.len(), 1);

    // Destroy B1 (target). A1's outgoing edge should remain (dangling).
    router.destroy_beta(B1);

    // A1 can still update its signal without error
    router.set_alpha_demand(A1, false);
    router.propagate();

    // No deliveries to A1 (no edges to it)
    let a1 = router.alpha_instances.get(&A1).unwrap();
    assert_eq!(a1.deliveries.len(), 0);

    // Verify A1's edge still exists in forward index (dangling)
    assert!(router
        .alpha_to_beta_fwd
        .get(&A1)
        .unwrap()
        .contains(&B1));
}

#[test]
fn sm_creation_no_eager_delivery() {
    let mut router = Router::new(16);

    // Create SMs but don't establish any edges
    router.create_alpha(A1, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    router.propagate();

    // No deliveries — empty edge sets are well-defined but not eagerly delivered
    let a1 = router.alpha_instances.get(&A1).unwrap();
    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(a1.deliveries.len(), 0);
    assert_eq!(b1.deliveries.len(), 0);
}

#[test]
fn round_semantics_multiple_inputs_delivered_independently() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());
    router.create_gamma(G1);

    // A1 -> B1 (DemandInput) and G1 -> B1 (ConfigInput)
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_gamma_to_beta_edges(G1, vec![B1]);

    // Set both signals before propagating
    router.set_alpha_demand(A1, true);
    router.set_gamma_value(G1, 99);

    router.propagate();

    // B1 should receive both DemandInput and ConfigInput as separate deliveries
    let b1 = router.beta_instances.get(&B1).unwrap();
    let demand_count = b1
        .deliveries
        .iter()
        .filter(|inp| matches!(inp, BetaSmInput::DemandInput(_)))
        .count();
    let config_count = b1
        .deliveries
        .iter()
        .filter(|inp| matches!(inp, BetaSmInput::ConfigInput(_)))
        .count();

    assert_eq!(demand_count, 1);
    assert_eq!(config_count, 1);

    // Verify values
    assert!(b1
        .deliveries
        .iter()
        .any(|inp| *inp == BetaSmInput::DemandInput(1)));
    assert!(b1
        .deliveries
        .iter()
        .any(|inp| *inp == BetaSmInput::ConfigInput(vec![99])));
}

#[test]
fn sm_destruction_removes_outgoing_edges() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_alpha(A2, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    // Both A1, A2 -> B1
    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.set_alpha_to_beta_edges(A2, vec![B1]);
    router.set_alpha_demand(A1, true);
    router.set_alpha_demand(A2, true);

    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(*b1.deliveries.last().unwrap(), BetaSmInput::DemandInput(2));

    // Destroy A2 — its outgoing edge is removed, B1 re-aggregates
    router.destroy_alpha(A2);
    router.propagate();

    let b1 = router.beta_instances.get(&B1).unwrap();
    assert_eq!(*b1.deliveries.last().unwrap(), BetaSmInput::DemandInput(1));
}

#[test]
fn dangling_edge_to_dead_sm_is_noop() {
    let mut router = Router::new(16);
    router.create_alpha(A1, AlphaSm::new());
    router.create_beta(B1, BetaSm::new());

    router.set_alpha_to_beta_edges(A1, vec![B1]);
    router.propagate();

    // Destroy B1
    router.destroy_beta(B1);

    // Setting an edge to a dead SM is well-defined (no panic, no delivery)
    router.set_alpha_to_beta_edges(A1, vec![B1, B2]);
    router.propagate();

    // B1 is gone, B2 was never created — no deliveries anywhere
    assert!(!router.beta_instances.contains_key(&B1));
    assert!(!router.beta_instances.contains_key(&B2));
}
